# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Actual_Chemicals.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Actual Chemical On hand View")
        MainWindow.setFixedSize(800, 557)
        MainWindow.setStyleSheet("QMainWindow { background-color: #D9E9CF; }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget { background-color: #D9E9CF; margin: 0px; padding: 0px; }")
        self.centralwidget.setObjectName("centralwidget")
        self.actualChemicalOnHand = QtWidgets.QTableWidget(self.centralwidget)
        self.actualChemicalOnHand.setGeometry(QtCore.QRect(0, 0, 801, 501))
        self.actualChemicalOnHand.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F5F5;\n"
"    gridline-color: #D8EDE0;\n"
"    border: none;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #1B4332;\n"
"    selection-background-color: #C6F6D5;\n"
"    selection-color: #1B4332;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 4px 8px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #C6F6D5;\n"
"    color: #1B4332;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-right: 1px solid #1B4332;\n"
"    padding: 6px 8px;\n"
"    font: bold 11pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"}\n"
"QHeaderView::section:vertical {\n"
"    background-color: #F0F0F0;\n"
"    color: #1B4332;\n"
"    border-right: 1px solid #D1D9CC;\n"
"}\n"
"QHeaderView { background-color: transparent; border: none; }\n"
"QTableCornerButton::section { background-color: #2D6A4F; border: none; }\n"
"QScrollBar:vertical { background: #E8F0EC; width: 11px; border-radius: 5px; }\n"
"QScrollBar::handle:vertical { background: #1B4332; border-radius: 5px; min-height: 25px; }\n"
"QScrollBar::handle:vertical:hover { background: #0F2A20; }\n"
"QScrollBar::handle:vertical:pressed { background: #081A13; }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; }\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical { background: transparent; }\n"
"QScrollBar:horizontal { background: #E8F0EC; height: 11px; border-radius: 5px; }\n"
"QScrollBar::handle:horizontal { background: #1B4332; border-radius: 5px; min-width: 25px; }\n"
"QScrollBar::handle:horizontal:hover { background: #0F2A20; }\n"
"QScrollBar::handle:horizontal:pressed { background: #081A13; }\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; }\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal { background: transparent; }")
        self.actualChemicalOnHand.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.actualChemicalOnHand.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.actualChemicalOnHand.setObjectName("acutalChemicalOnHand")
        self.actualChemicalOnHand.setColumnCount(3)
        self.actualChemicalOnHand.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualChemicalOnHand.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualChemicalOnHand.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualChemicalOnHand.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualChemicalOnHand.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualChemicalOnHand.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualChemicalOnHand.setItem(4, 0, item)
        self.actualChemicalOnHand.horizontalHeader().setDefaultSectionSize(250)
        self.actualChemicalOnHand.horizontalHeader().setSortIndicatorShown(False)
        self.actualChemicalOnHand.horizontalHeader().setStretchLastSection(True)
        self.actualChemicalOnHand.verticalHeader().setDefaultSectionSize(40)
        self.addRowBtn_chem = QtWidgets.QPushButton(self.centralwidget)
        self.addRowBtn_chem.setGeometry(QtCore.QRect(30, 507, 741, 44))
        self.addRowBtn_chem.setStyleSheet("QPushButton { background-color: transparent; color: #2D6A4F; border: 1.5px dashed #2D6A4F; border-radius: 8px; padding: 6px 12px; font: 12pt \"Segoe UI\"; } QPushButton:hover { background-color: #e8f5e9; }")
        self.addRowBtn_chem.setObjectName("addRowBtn_chem")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("ACTUAL CHEMICALS ON HAND", "ACTUAL CHEMICALS ON HAND"))
        item = self.actualChemicalOnHand.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.actualChemicalOnHand.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.actualChemicalOnHand.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.actualChemicalOnHand.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.actualChemicalOnHand.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.actualChemicalOnHand.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Actual Chemical/s On Hand"))
        item = self.actualChemicalOnHand.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.actualChemicalOnHand.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Remarks"))
        __sortingEnabled = self.actualChemicalOnHand.isSortingEnabled()
        self.actualChemicalOnHand.setSortingEnabled(False)
        self.actualChemicalOnHand.setSortingEnabled(__sortingEnabled)
        self.addRowBtn_chem.setText(_translate("MainWindow", "+ Add a Row"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
