# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docx_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocxViewer(object):
    def setupUi(self, DocxViewer):
        DocxViewer.setObjectName("DocxViewer")
        DocxViewer.setMinimumSize(1416, 988)
        DocxViewer.setStyleSheet("\n"
"\n"
"QMainWindow, QWidget#centralwidget { background-color: #EBEBEB; }\n"
"\n"
"QMenuBar {\n"
"    background-color: #2D6A4F; color: #FFFFFF;\n"
"    font: 11pt \"Segoe UI\"; padding: 2px 4px; border: none;\n"
"}\n"
"QMenuBar::item { padding: 4px 12px; border-radius: 4px; }\n"
"QMenuBar::item:selected { background-color: rgba(255,255,255,0.20); }\n"
"QMenu {\n"
"    background-color: #FFFFFF; color: #1A3C2A;\n"
"    border: 1px solid #C6F6D5; border-radius: 6px; font: 10pt \"Segoe UI\";\n"
"}\n"
"QMenu::item { padding: 6px 20px; }\n"
"QMenu::item:selected { background-color: #2D6A4F; color: #FFFFFF; }\n"
"QMenu::separator { height: 1px; background-color: #C6F6D5; margin: 4px 10px; }\n"
"\n"
"QToolBar {\n"
"    background-color: #2D6A4F; border: none; spacing: 4px; padding: 4px 8px;\n"
"}\n"
"QToolBar::separator { background-color: rgba(255,255,255,0.30); width: 1px; margin: 4px 6px; }\n"
"QToolBar QToolButton {\n"
"    background-color: transparent; color: #FFFFFF;\n"
"    border: 1px solid transparent; border-radius: 6px;\n"
"    padding: 5px 10px; font: 10pt \"Segoe UI\";\n"
"}\n"
"QToolBar QToolButton:hover { background-color: rgba(255,255,255,0.18); border: 1px solid rgba(255,255,255,0.35); }\n"
"QToolBar QToolButton:pressed { background-color: rgba(255,255,255,0.28); }\n"
"\n"
"QStatusBar {\n"
"    background-color: #2D6A4F; color: #C6F6D5;\n"
"    font: 9pt \"Segoe UI\"; border-top: 1px solid #1F4D2C; padding: 2px 8px;\n"
"}\n"
"QStatusBar::item { border: none; }\n"
"\n"
"QWidget#filesPanel, QWidget#tocPanel { background-color: #D9E9CF; }\n"
"\n"
"QLabel#filesPanelHeader, QLabel#tocPanelHeader {\n"
"    background-color: #2D6A4F; color: #FFFFFF;\n"
"    font: bold 10pt \"Segoe UI\"; padding: 8px 12px;\n"
"}\n"
"\n"
"QSplitter#leftSplitter::handle { background-color: #2D6A4F; }\n"
"QSplitter#leftSplitter::handle:hover { background-color: #52b788; }\n"
"\n"
"QListWidget#filesList, QListWidget#tocList {\n"
"    background-color: #D9E9CF; color: #1A3C2A;\n"
"    border: none; font: 10pt \"Segoe UI\"; outline: none;\n"
"}\n"
"QListWidget#filesList::item, QListWidget#tocList::item {\n"
"    padding: 7px 12px; border-bottom: 1px solid #C2D9BA;\n"
"}\n"
"QListWidget#filesList::item:hover, QListWidget#tocList::item:hover {\n"
"    background-color: #C6E6D3; color: #0E3B21;\n"
"}\n"
"QListWidget#filesList::item:selected, QListWidget#tocList::item:selected {\n"
"    background-color: #2D6A4F; color: #FFFFFF; border-left: 3px solid #C6F6D5;\n"
"}\n"
"\n"
"QScrollBar:vertical { background: #D9E9CF; width: 8px; margin: 0; border-radius: 4px; }\n"
"QScrollBar::handle:vertical { background: #7AB99A; border-radius: 4px; min-height: 28px; }\n"
"QScrollBar::handle:vertical:hover { background: #2D6A4F; }\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical { height: 0; }\n"
"QScrollBar:horizontal { background: #D9E9CF; height: 8px; border-radius: 4px; }\n"
"QScrollBar::handle:horizontal { background: #7AB99A; border-radius: 4px; min-width: 28px; }\n"
"QScrollBar::handle:horizontal:hover { background: #2D6A4F; }\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal { width: 0; }\n"
"\n"
"QScrollArea#pageScrollArea { background-color: #D9E9CF; border: none; }\n"
"QWidget#scrollAreaContent { background-color: #D9E9CF; }\n"
"\n"
"QFrame#paperPage1, QFrame#paperPage2 {\n"
"    background-color: #FFFFFF; border: none;\n"
"}\n"
"\n"
"QLabel#companyName {\n"
"    color: #1A3C2A; font: bold 18pt \"Segoe UI\";\n"
"}\n"
"QLabel#companyName2 {\n"
"    color: #1A3C2A; font: bold 14pt \"Segoe UI\";\n"
"}\n"
"QLabel#companyTagline {\n"
"    color: #2D6A4F; font: 10pt \"Segoe UI\";\n"
"}\n"
"QFrame#headerDivider, QFrame#headerDivider2 {\n"
"    background-color: #2D6A4F; max-height: 2px; border: none;\n"
"}\n"
"QLabel#docTitleLabel {\n"
"    color: #1A3C2A; font: bold 13pt \"Segoe UI\"; padding: 6px 0 2px 0;\n"
"}\n"
"QLabel#metaLabel { color: #4A7A5A; font: 9pt \"Segoe UI\"; }\n"
"QFrame#innerDivider { background-color: #C6F6D5; max-height: 1px; border: none; }\n"
"QLabel#sectionLabel {\n"
"    color: #2D6A4F; font: bold 11pt \"Segoe UI\"; padding: 10px 0 4px 0;\n"
"}\n"
"QLabel#continuedLabel2 {\n"
"    color: #2D6A4F; font: italic 9pt \"Segoe UI\"; padding: 4px 0 8px 0;\n"
"}\n"
"QLabel#notesLabel {\n"
"    color: #2D6A4F; font: bold 11pt \"Segoe UI\"; padding: 10px 0 4px 0;\n"
"}\n"
"QLabel#pageFooter1, QLabel#pageFooter2 {\n"
"    color: #7AB99A; font: 8pt \"Segoe UI\";\n"
"    padding: 6px 0 0 0; border-top: 1px solid #C6F6D5;\n"
"}\n"
"\n"
"QTableWidget#inventoryTable1,\n"
"QTableWidget#inventoryTable2 {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F4FBF6;\n"
"    gridline-color: #C6F6D5;\n"
"    color: #1A3C2A; font: 10pt \"Segoe UI\";\n"
"    border: 1px solid #C6F6D5;\n"
"    selection-background-color: #D6EBDD;\n"
"    selection-color: #0E3B21;\n"
"}\n"
"QTableWidget#inventoryTable1::item,\n"
"QTableWidget#inventoryTable2::item {\n"
"    padding: 5px 8px; border: none;\n"
"}\n"
"QTableWidget#inventoryTable1::item:hover,\n"
"QTableWidget#inventoryTable2::item:hover {\n"
"    background-color: #EAF7EE;\n"
"}\n"
"QTableWidget#inventoryTable1 QHeaderView::section,\n"
"QTableWidget#inventoryTable2 QHeaderView::section {\n"
"    background-color: #2D6A4F; color: #FFFFFF;\n"
"    font: bold 10pt \"Segoe UI\"; padding: 7px 8px;\n"
"    border: none; border-right: 1px solid #3A7A5A;\n"
"    border-bottom: 2px solid #C6F6D5;\n"
"}\n"
"QTableWidget#inventoryTable1 QHeaderView::section:hover,\n"
"QTableWidget#inventoryTable2 QHeaderView::section:hover {\n"
"    background-color: #1F4D2C;\n"
"}\n"
"\n"
"QTextEdit#notesEdit {\n"
"    background-color: #FAFFFE; color: #1A3C2A;\n"
"    font: 10pt \"Segoe UI\"; border: 1px solid #C6F6D5;\n"
"    border-radius: 4px; padding: 8px;\n"
"    selection-background-color: #D6EBDD;\n"
"}\n"
"QTextEdit#notesEdit:focus {\n"
"    border: 1px solid #2D6A4F; background-color: #EAF7EE;\n"
"}\n"
"\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(DocxViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.mainHLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainHLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHLayout.setSpacing(0)
        self.mainHLayout.setObjectName("mainHLayout")
        self.leftPanelVLayout = QtWidgets.QVBoxLayout()
        self.leftPanelVLayout.setContentsMargins(0, 0, 0, 0)
        self.leftPanelVLayout.setSpacing(0)
        self.leftPanelVLayout.setObjectName("leftPanelVLayout")
        self.leftSplitter = QtWidgets.QSplitter(self.centralwidget)
        self.leftSplitter.setOrientation(QtCore.Qt.Vertical)
        self.leftSplitter.setHandleWidth(3)
        self.leftSplitter.setChildrenCollapsible(False)
        self.leftSplitter.setObjectName("leftSplitter")
        self.filesPanel = QtWidgets.QWidget(self.leftSplitter)
        self.filesPanel.setMinimumSize(QtCore.QSize(220, 180))
        self.filesPanel.setObjectName("filesPanel")
        self.filesPanelVLayout = QtWidgets.QVBoxLayout(self.filesPanel)
        self.filesPanelVLayout.setContentsMargins(0, 0, 0, 0)
        self.filesPanelVLayout.setSpacing(0)
        self.filesPanelVLayout.setObjectName("filesPanelVLayout")
        self.filesPanelHeader = QtWidgets.QLabel(self.filesPanel)
        self.filesPanelHeader.setObjectName("filesPanelHeader")
        self.filesPanelVLayout.addWidget(self.filesPanelHeader)
        self.filesList = QtWidgets.QListWidget(self.filesPanel)
        self.filesList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.filesList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.filesList.setObjectName("filesList")
        item = QtWidgets.QListWidgetItem()
        self.filesList.addItem(item)
        self.filesPanelVLayout.addWidget(self.filesList)
        self.tocPanel = QtWidgets.QWidget(self.leftSplitter)
        self.tocPanel.setMinimumSize(QtCore.QSize(220, 150))
        self.tocPanel.setObjectName("tocPanel")
        self.tocPanelVLayout = QtWidgets.QVBoxLayout(self.tocPanel)
        self.tocPanelVLayout.setContentsMargins(0, 0, 0, 0)
        self.tocPanelVLayout.setSpacing(0)
        self.tocPanelVLayout.setObjectName("tocPanelVLayout")
        self.tocPanelHeader = QtWidgets.QLabel(self.tocPanel)
        self.tocPanelHeader.setObjectName("tocPanelHeader")
        self.tocPanelVLayout.addWidget(self.tocPanelHeader)
        self.tocList = QtWidgets.QListWidget(self.tocPanel)
        self.tocList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tocList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tocList.setObjectName("tocList")
        item = QtWidgets.QListWidgetItem()
        self.tocList.addItem(item)
        self.tocPanelVLayout.addWidget(self.tocList)
        self.leftPanelVLayout.addWidget(self.leftSplitter)
        self.mainHLayout.addLayout(self.leftPanelVLayout)
        self.pageScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.pageScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.pageScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.pageScrollArea.setWidgetResizable(True)
        self.pageScrollArea.setObjectName("pageScrollArea")
        self.scrollAreaContent = QtWidgets.QWidget()
        self.scrollAreaContent.setGeometry(QtCore.QRect(0, 0, 1148, 1105))
        self.scrollAreaContent.setObjectName("scrollAreaContent")
        self.scrollContentVLayout = QtWidgets.QVBoxLayout(self.scrollAreaContent)
        self.scrollContentVLayout.setContentsMargins(36, 28, 36, 36)
        self.scrollContentVLayout.setSpacing(24)
        self.scrollContentVLayout.setObjectName("scrollContentVLayout")
        self.paperPage1 = QtWidgets.QFrame(self.scrollAreaContent)
        self.paperPage1.setFrameShape(QtWidgets.QFrame.Box)
        self.paperPage1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.paperPage1.setLineWidth(0)
        self.paperPage1.setObjectName("paperPage1")
        self.paperLayout1 = QtWidgets.QVBoxLayout(self.paperPage1)
        self.paperLayout1.setContentsMargins(52, 44, 52, 44)
        self.paperLayout1.setSpacing(8)
        self.paperLayout1.setObjectName("paperLayout1")
        self.companyName = QtWidgets.QLabel(self.paperPage1)
        self.companyName.setObjectName("companyName")
        self.paperLayout1.addWidget(self.companyName)
        self.companyTagline = QtWidgets.QLabel(self.paperPage1)
        self.companyTagline.setObjectName("companyTagline")
        self.paperLayout1.addWidget(self.companyTagline)
        self.headerDivider = QtWidgets.QFrame(self.paperPage1)
        self.headerDivider.setFrameShape(QtWidgets.QFrame.HLine)
        self.headerDivider.setFrameShadow(QtWidgets.QFrame.Plain)
        self.headerDivider.setObjectName("headerDivider")
        self.paperLayout1.addWidget(self.headerDivider)
        self.docTitleLabel = QtWidgets.QLabel(self.paperPage1)
        self.docTitleLabel.setObjectName("docTitleLabel")
        self.paperLayout1.addWidget(self.docTitleLabel)
        self.metaLabel = QtWidgets.QLabel(self.paperPage1)
        self.metaLabel.setObjectName("metaLabel")
        self.paperLayout1.addWidget(self.metaLabel)
        self.innerDivider = QtWidgets.QFrame(self.paperPage1)
        self.innerDivider.setFrameShape(QtWidgets.QFrame.HLine)
        self.innerDivider.setFrameShadow(QtWidgets.QFrame.Plain)
        self.innerDivider.setObjectName("innerDivider")
        self.paperLayout1.addWidget(self.innerDivider)
        self.sectionLabel = QtWidgets.QLabel(self.paperPage1)
        self.sectionLabel.setObjectName("sectionLabel")
        self.paperLayout1.addWidget(self.sectionLabel)
        self.inventoryTable1 = QtWidgets.QTableWidget(self.paperPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inventoryTable1.sizePolicy().hasHeightForWidth())
        self.inventoryTable1.setSizePolicy(sizePolicy)
        self.inventoryTable1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inventoryTable1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.inventoryTable1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.inventoryTable1.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.inventoryTable1.setTabKeyNavigation(True)
        self.inventoryTable1.setAlternatingRowColors(True)
        self.inventoryTable1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.inventoryTable1.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.inventoryTable1.setShowGrid(True)
        self.inventoryTable1.setGridStyle(QtCore.Qt.SolidLine)
        self.inventoryTable1.setRowCount(10)
        self.inventoryTable1.setColumnCount(6)
        self.inventoryTable1.setObjectName("inventoryTable1")
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(5, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(6, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(7, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(8, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.inventoryTable1.setItem(9, 5, item)
        self.inventoryTable1.horizontalHeader().setDefaultSectionSize(157)
        self.paperLayout1.addWidget(self.inventoryTable1)
        self.pageFooter1 = QtWidgets.QLabel(self.paperPage1)
        self.pageFooter1.setObjectName("pageFooter1")
        self.paperLayout1.addWidget(self.pageFooter1)
        self.scrollContentVLayout.addWidget(self.paperPage1)
        self.paperPage2 = QtWidgets.QFrame(self.scrollAreaContent)
        self.paperPage2.setFrameShape(QtWidgets.QFrame.Box)
        self.paperPage2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.paperPage2.setLineWidth(0)
        self.paperPage2.setObjectName("paperPage2")
        self.paperLayout2 = QtWidgets.QVBoxLayout(self.paperPage2)
        self.paperLayout2.setContentsMargins(52, 44, 52, 44)
        self.paperLayout2.setSpacing(8)
        self.paperLayout2.setObjectName("paperLayout2")
        self.companyName2 = QtWidgets.QLabel(self.paperPage2)
        self.companyName2.setObjectName("companyName2")
        self.paperLayout2.addWidget(self.companyName2)
        self.headerDivider2 = QtWidgets.QFrame(self.paperPage2)
        self.headerDivider2.setFrameShape(QtWidgets.QFrame.HLine)
        self.headerDivider2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.headerDivider2.setObjectName("headerDivider2")
        self.paperLayout2.addWidget(self.headerDivider2)
        self.notesLabel = QtWidgets.QLabel(self.paperPage2)
        self.notesLabel.setObjectName("notesLabel")
        self.paperLayout2.addWidget(self.notesLabel)
        self.notesEdit = QtWidgets.QTextEdit(self.paperPage2)
        self.notesEdit.setMinimumSize(QtCore.QSize(0, 120))
        self.notesEdit.setAcceptRichText(False)
        self.notesEdit.setObjectName("notesEdit")
        self.paperLayout2.addWidget(self.notesEdit)
        self.pageFooter2 = QtWidgets.QLabel(self.paperPage2)
        self.pageFooter2.setObjectName("pageFooter2")
        self.paperLayout2.addWidget(self.pageFooter2)
        self.scrollContentVLayout.addWidget(self.paperPage2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.scrollContentVLayout.addItem(spacerItem)
        self.pageScrollArea.setWidget(self.scrollAreaContent)
        self.mainHLayout.addWidget(self.pageScrollArea)
        DocxViewer.setCentralWidget(self.centralwidget)
        self.mainToolBar = QtWidgets.QToolBar(DocxViewer)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setIconSize(QtCore.QSize(16, 16))
        self.mainToolBar.setFloatable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        DocxViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.menubar = QtWidgets.QMenuBar(DocxViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1416, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DocxViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DocxViewer)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        DocxViewer.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(DocxViewer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRefresh = QtWidgets.QAction(DocxViewer)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionExport = QtWidgets.QAction(DocxViewer)
        self.actionExport.setObjectName("actionExport")
        self.actionPrint = QtWidgets.QAction(DocxViewer)
        self.actionPrint.setObjectName("actionPrint")
        self.actionZoomIn = QtWidgets.QAction(DocxViewer)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(DocxViewer)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionZoomReset = QtWidgets.QAction(DocxViewer)
        self.actionZoomReset.setObjectName("actionZoomReset")
        self.actionFind = QtWidgets.QAction(DocxViewer)
        self.actionFind.setObjectName("actionFind")
        self.actionClose = QtWidgets.QAction(DocxViewer)
        self.actionClose.setObjectName("actionClose")
        self.actionAbout = QtWidgets.QAction(DocxViewer)
        self.actionAbout.setObjectName("actionAbout")
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionRefresh)
        self.mainToolBar.addAction(self.actionExport)
        self.mainToolBar.addAction(self.actionPrint)
        self.mainToolBar.addAction(self.actionZoomIn)
        self.mainToolBar.addAction(self.actionZoomOut)
        self.mainToolBar.addAction(self.actionFind)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuView.addAction(self.actionZoomIn)
        self.menuView.addAction(self.actionZoomOut)
        self.menuView.addAction(self.actionZoomReset)
        self.menuEdit.addAction(self.actionFind)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DocxViewer)
        QtCore.QMetaObject.connectSlotsByName(DocxViewer)

    def retranslateUi(self, DocxViewer):
        _translate = QtCore.QCoreApplication.translate
        DocxViewer.setWindowTitle(_translate("DocxViewer", "Raionn Pest Solutions — Document Viewer"))
        self.filesPanelHeader.setText(_translate("DocxViewer", " Available Files"))
        __sortingEnabled = self.filesList.isSortingEnabled()
        self.filesList.setSortingEnabled(False)
        item = self.filesList.item(0)
        item.setText(_translate("DocxViewer", "Sample Sir Dong"))
        self.filesList.setSortingEnabled(__sortingEnabled)
        self.tocPanelHeader.setText(_translate("DocxViewer", "Table of Contents"))
        __sortingEnabled = self.tocList.isSortingEnabled()
        self.tocList.setSortingEnabled(False)
        item = self.tocList.item(0)
        item.setText(_translate("DocxViewer", "1. Bakit Panot si sir Dong?"))
        self.tocList.setSortingEnabled(__sortingEnabled)
        self.companyName.setText(_translate("DocxViewer", "Raionn Pest Solutions"))
        self.companyTagline.setText(_translate("DocxViewer", "Professional Pest Control and Inventory Management  |  raionnpest@gmail.com"))
        self.docTitleLabel.setText(_translate("DocxViewer", "Inventory Report — Q1 2025"))
        self.metaLabel.setText(_translate("DocxViewer", "Generated: January 31, 2025  |  Prepared by: Admin  |  Status: Active"))
        self.sectionLabel.setText(_translate("DocxViewer", "Inventory Table"))
        self.inventoryTable1.setSortingEnabled(True)
        item = self.inventoryTable1.horizontalHeaderItem(0)
        item.setText(_translate("DocxViewer", "Date of Treatment"))
        item = self.inventoryTable1.horizontalHeaderItem(1)
        item.setText(_translate("DocxViewer", "Name of Client"))
        item = self.inventoryTable1.horizontalHeaderItem(2)
        item.setText(_translate("DocxViewer", "Time of Treatment"))
        item = self.inventoryTable1.horizontalHeaderItem(3)
        item.setText(_translate("DocxViewer", "Chemical/s Used"))
        item = self.inventoryTable1.horizontalHeaderItem(4)
        item.setText(_translate("DocxViewer", "Actual Chemical/s Used"))
        item = self.inventoryTable1.horizontalHeaderItem(5)
        item.setText(_translate("DocxViewer", "Remarks"))
        __sortingEnabled = self.inventoryTable1.isSortingEnabled()
        self.inventoryTable1.setSortingEnabled(False)
        self.inventoryTable1.setSortingEnabled(__sortingEnabled)
        self.pageFooter1.setText(_translate("DocxViewer", "Raionn Pest Solutions — Confidential                                                                    Page 1 of 2"))
        self.companyName2.setText(_translate("DocxViewer", "Raionn Pest Solutions"))
        self.notesLabel.setText(_translate("DocxViewer", "Statement (click to edit)"))
        self.notesEdit.setPlaceholderText(_translate("DocxViewer", "Click here to type your notes, observations, or remarks for this report..."))
        self.pageFooter2.setText(_translate("DocxViewer", "Raionn Pest Solutions © 2025 — Confidential                                                                    Page 2 of 2"))
        self.menuFile.setTitle(_translate("DocxViewer", "File"))
        self.menuView.setTitle(_translate("DocxViewer", "View"))
        self.menuEdit.setTitle(_translate("DocxViewer", "Edit"))
        self.menuHelp.setTitle(_translate("DocxViewer", "Help"))
        self.actionOpen.setText(_translate("DocxViewer", "Open"))
        self.actionOpen.setToolTip(_translate("DocxViewer", "Open a document  (Ctrl+O)"))
        self.actionOpen.setShortcut(_translate("DocxViewer", "Ctrl+O"))
        self.actionRefresh.setText(_translate("DocxViewer", "Refresh"))
        self.actionRefresh.setToolTip(_translate("DocxViewer", "Refresh file list  (F5)"))
        self.actionRefresh.setShortcut(_translate("DocxViewer", "F5"))
        self.actionExport.setText(_translate("DocxViewer", "Export"))
        self.actionExport.setToolTip(_translate("DocxViewer", "Export document  (Ctrl+E)"))
        self.actionExport.setShortcut(_translate("DocxViewer", "Ctrl+E"))
        self.actionPrint.setText(_translate("DocxViewer", "Print"))
        self.actionPrint.setToolTip(_translate("DocxViewer", "Print document  (Ctrl+P)"))
        self.actionPrint.setShortcut(_translate("DocxViewer", "Ctrl+P"))
        self.actionZoomIn.setText(_translate("DocxViewer", "Zoom In"))
        self.actionZoomIn.setToolTip(_translate("DocxViewer", "Zoom in  (Ctrl++)"))
        self.actionZoomIn.setShortcut(_translate("DocxViewer", "Ctrl+="))
        self.actionZoomOut.setText(_translate("DocxViewer", "Zoom Out"))
        self.actionZoomOut.setToolTip(_translate("DocxViewer", "Zoom out  (Ctrl+-)"))
        self.actionZoomOut.setShortcut(_translate("DocxViewer", "Ctrl+-"))
        self.actionZoomReset.setText(_translate("DocxViewer", "Reset Zoom"))
        self.actionZoomReset.setShortcut(_translate("DocxViewer", "Ctrl+0"))
        self.actionFind.setText(_translate("DocxViewer", "Find"))
        self.actionFind.setToolTip(_translate("DocxViewer", "Find in document  (Ctrl+F)"))
        self.actionFind.setShortcut(_translate("DocxViewer", "Ctrl+F"))
        self.actionClose.setText(_translate("DocxViewer", "Close"))
        self.actionClose.setShortcut(_translate("DocxViewer", "Ctrl+W"))
        self.actionAbout.setText(_translate("DocxViewer", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DocxViewer = QtWidgets.QMainWindow()
    ui = Ui_DocxViewer()
    ui.setupUi(DocxViewer)
    DocxViewer.show()
    sys.exit(app.exec_())
