# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intro.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

base_dir = os.path.dirname(__file__)
image_path = os.path.join(base_dir, "assets")

class Ui_Intro(object):
    def setupUi(self, Intro):
        Intro.setObjectName("Raionn Admin")
        Intro.setFixedSize(822, 485)
        self.centralwidget = QtWidgets.QWidget(Intro)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 831, 491))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(f"{image_path}/ac5ef8e8-980b-4953-9c2c-731a2af90d63.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Progress_Loader = QtWidgets.QProgressBar(self.centralwidget)
        self.Progress_Loader.setGeometry(QtCore.QRect(120, 440, 611, 23))
        self.Progress_Loader.setProperty("value", 24)
        self.Progress_Loader.setObjectName("Progress_Loader")
        self.indicator = QtWidgets.QLabel(self.centralwidget)
        self.indicator.setGeometry(QtCore.QRect(260, 390, 327, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.indicator.setFont(font)
        self.indicator.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.indicator.setAlignment(QtCore.Qt.AlignCenter)
        self.indicator.setObjectName("indicator")
        Intro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Intro)
        QtCore.QMetaObject.connectSlotsByName(Intro)

    def retranslateUi(self, Intro):
        _translate = QtCore.QCoreApplication.translate
        Intro.setWindowTitle(_translate("Raionn Admin", "Raionn Admin"))
        self.indicator.setText(_translate("Raionn Admin", "Loading......"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Intro = QtWidgets.QMainWindow()
    ui = Ui_Intro()
    ui.setupUi(Intro)
    Intro.show()
    sys.exit(app.exec_())
