# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

base_dir = os.path.dirname(__file__)
image_path = os.path.join(base_dir, "assets")

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setFixedSize(410, 559)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Login.setFont(font)
        Login.setStyleSheet("/* Background only for the stacked widget */\n"
"\n"
"\n"
"\n"
"/* Make stacked widget pages transparent */\n"
"#stackedWidget > QWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Optional: Make labels transparent */\n"
"#stackedWidget QLabel {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Optional: Style input fields cleanly */\n"
"#stackedWidget QLineEdit {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Optional: Style buttons */\n"
"#stackedWidget QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* Modern White Input Fields with Dark Hover (fixed for Qt) */\n"
"QLineEdit#usernameEdit, QLineEdit#passwordEdit {\n"
"    background-color: white;\n"
"    color: #333333;\n"
"    border: 1.5px solid #DCDCDC;\n"
"    border-radius: 10px;\n"
"    padding: 8px 35px 8px 10px; /* extra space for eye icon in password */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QLineEdit#usernameEdit:hover, QLineEdit#passwordEdit:hover {\n"
"    background-color: #F0F0F0;\n"
"    border: 1.5px solid #BFBFBF;\n"
"}\n"
"\n"
"/* Focus */\n"
"QLineEdit#usernameEdit:focus, QLineEdit#passwordEdit:focus {\n"
"    border: 2px solid #4CAF50;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Placeholder text */\n"
"QLineEdit#usernameEdit::placeholder,\n"
"QLineEdit#passwordEdit::placeholder {\n"
"    color: #9E9E9E;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.containerlogin = QtWidgets.QWidget(self.centralwidget)
        self.containerlogin.setGeometry(QtCore.QRect(10, 10, 391, 541))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        self.containerlogin.setFont(font)
        self.containerlogin.setAutoFillBackground(False)
        self.containerlogin.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 220);  /* frosted white */\n"
"    border-radius: 15px;                         \n"
"    padding: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #346739;      /* lighter green */\n"
"    border-left-color: #79AE6F;     \n"
"    border-bottom-color: #008000;   /* darker green */\n"
"    border-right-color: #008000;\n"
"}")
        self.containerlogin.setObjectName("containerlogin")
        self.usernameEdit = QtWidgets.QLineEdit(self.containerlogin)
        self.usernameEdit.setGeometry(QtCore.QRect(50, 260, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.usernameEdit.setStyleSheet("QLineEdit {\n"
"    background-color: white;                /* base white */\n"
"    color: #333333;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #FFFFFF;              /* lighter top */\n"
"    border-left-color: #FFFFFF;             /* lighter left */\n"
"    border-bottom-color: #BFBFBF;           /* darker bottom */\n"
"    border-right-color: #BFBFBF;            /* darker right */\n"
"    border-radius: 10px;                    \n"
"    padding: 8px 10px;\n"
"    font-size: 14px;\n"
"    transition: all 0.2s ease;              /* smooth hover/focus transitions */\n"
"}\n"
"\n"
"/* Hover Effect — slightly darker background & subtle border change */\n"
"QLineEdit:hover {\n"
"    background-color: #F0F0F0;\n"
"    border-top-color: #F5F5F5;\n"
"    border-left-color: #F5F5F5;\n"
"    border-bottom-color: #AAAAAA;\n"
"    border-right-color: #AAAAAA;\n"
"}\n"
"\n"
"/* Focus Effect — bright green border with 3D depth */\n"
"QLineEdit:focus {\n"
"    border-top-color: #4CAF50;              /* brighter green top/left */\n"
"    border-left-color: #4CAF50;\n"
"    border-bottom-color: #388E3C;           /* darker green bottom/right */\n"
"    border-right-color: #388E3C;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Placeholder text */\n"
"QLineEdit::placeholder {\n"
"    color: #9E9E9E;\n"
"}")
        self.usernameEdit.setInputMask("")
        self.usernameEdit.setText("")
        self.usernameEdit.setMaxLength(32767)
        self.usernameEdit.setFrame(True)
        self.usernameEdit.setReadOnly(False)
        self.usernameEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.usernameEdit.setObjectName("usernameEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.containerlogin)
        self.passwordEdit.setGeometry(QtCore.QRect(50, 360, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.passwordEdit.setStyleSheet("QLineEdit {\n"
"    background-color: white;                /* base white */\n"
"    color: #333333;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #FFFFFF;              /* lighter top */\n"
"    border-left-color: #FFFFFF;             /* lighter left */\n"
"    border-bottom-color: #BFBFBF;           /* darker bottom */\n"
"    border-right-color: #BFBFBF;            /* darker right */\n"
"    border-radius: 10px;                    \n"
"    padding: 8px 10px;\n"
"    font-size: 14px;\n"
"    transition: all 0.2s ease;              /* smooth hover/focus transitions */\n"
"}\n"
"\n"
"/* Hover Effect — slightly darker background & subtle border change */\n"
"QLineEdit:hover {\n"
"    background-color: #F0F0F0;\n"
"    border-top-color: #F5F5F5;\n"
"    border-left-color: #F5F5F5;\n"
"    border-bottom-color: #AAAAAA;\n"
"    border-right-color: #AAAAAA;\n"
"}\n"
"\n"
"/* Focus Effect — bright green border with 3D depth */\n"
"QLineEdit:focus {\n"
"    border-top-color: #4CAF50;              /* brighter green top/left */\n"
"    border-left-color: #4CAF50;\n"
"    border-bottom-color: #388E3C;           /* darker green bottom/right */\n"
"    border-right-color: #388E3C;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Placeholder text */\n"
"QLineEdit::placeholder {\n"
"    color: #9E9E9E;\n"
"}")
        self.passwordEdit.setInputMask("")
        self.passwordEdit.setText("")
        self.passwordEdit.setMaxLength(32767)
        self.passwordEdit.setFrame(True)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setReadOnly(False)
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginbutton = QtWidgets.QPushButton(self.containerlogin)
        self.loginbutton.setGeometry(QtCore.QRect(140, 460, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginbutton.setFont(font)
        self.loginbutton.setMouseTracking(False)
        self.loginbutton.setStyleSheet("QPushButton {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #5cd65c;      /* lighter top */\n"
"    border-left-color: #5cd65c;     /* lighter left */\n"
"    border-bottom-color: #1e7e34;   /* darker bottom */\n"
"    border-right-color: #1e7e34;    /* darker right */\n"
"    padding: 6px 12px;\n"
"    font: 15pt \"Segoe UI\";\n"
"    border-radius: 5px;             /* optional: rounded corners */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #218838;\n"
"    border-top-color: #66c266;\n"
"    border-left-color: #66c266;\n"
"    border-bottom-color: #1a6c2f;\n"
"    border-right-color: #1a6c2f;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;\n"
"    border-top-color: #1a6c2f;       /* invert for pressed */\n"
"    border-left-color: #1a6c2f;\n"
"    border-bottom-color: #66c266;\n"
"    border-right-color: #66c266;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #a8d5b7;\n"
"    color: #f0f0f0;\n"
"    border-top-color: #c0e0c2;\n"
"    border-left-color: #c0e0c2;\n"
"    border-bottom-color: #8ebf96;\n"
"    border-right-color: #8ebf96;\n"
"}")
        self.loginbutton.setObjectName("loginbutton")
        self.title = QtWidgets.QLabel(self.containerlogin)
        self.title.setGeometry(QtCore.QRect(30, 150, 321, 70))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none\n"
"}")
        self.title.setObjectName("title")
        self.title_2 = QtWidgets.QLabel(self.containerlogin)
        self.title_2.setGeometry(QtCore.QRect(40, 220, 119, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.title_2.setFont(font)
        self.title_2.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none\n"
"}")
        self.title_2.setObjectName("title_2")
        self.title_3 = QtWidgets.QLabel(self.containerlogin)
        self.title_3.setGeometry(QtCore.QRect(40, 320, 122, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.title_3.setFont(font)
        self.title_3.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    border: none\n"
"}")
        self.title_3.setObjectName("title_3")
        self.Logo = QtWidgets.QLabel(self.containerlogin)
        self.Logo.setGeometry(QtCore.QRect(87, -20, 221, 211))
        self.Logo.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"border: none;\n"
"}")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(f"{image_path}/Logo.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.usernameEdit.setPlaceholderText(_translate("Login", "Username"))
        self.passwordEdit.setPlaceholderText(_translate("Login", "Password"))
        self.loginbutton.setText(_translate("Login", "LOGIN"))
        self.title.setText(_translate("Login", "RAIONN ADMIN"))
        self.title_2.setText(_translate("Login", "USERNAME:"))
        self.title_3.setText(_translate("Login", "PASSWORD:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
