# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recycle_bin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

base_dir = os.path.dirname(__file__)
image_path = os.path.join(base_dir, "assets")

class Ui_RecycleBin(object):
    def setupUi(self, RecycleBin):
        RecycleBin.setObjectName("Recycle Bin")
        RecycleBin.setFixedSize(931, 717)
        self.centralwidget = QtWidgets.QWidget(RecycleBin)
        self.centralwidget.setObjectName("centralwidget")
        self.recycle_table = QtWidgets.QTableWidget(self.centralwidget)
        self.recycle_table.setGeometry(QtCore.QRect(0, 90, 931, 631))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.recycle_table.setFont(font)
        self.recycle_table.setStyleSheet("QTableWidget {\n"
"    background-color: #ffffff;            /* white background */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;            /* light top */\n"
"    border-left-color: #ffffff;           /* light left */\n"
"    border-bottom-color: #cccccc;         /* dark bottom */\n"
"    border-right-color: #cccccc;          /* dark right */\n"
"    gridline-color: #e6e6e6;\n"
"    font: 13pt \"Segoe UI\";\n"
"    selection-background-color: #2ecc71;\n"
"    selection-color: white;\n"
"    alternate-background-color: #f9f9f9;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e6e6e6;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #2ecc71;   /* green when selected */\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: #f0f0f0;   /* darker on hover */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f3f3f3;\n"
"    color: #333333;\n"
"    padding: 6px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #cccccc;\n"
"    border-right-color: #cccccc;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #f3f3f3;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #cccccc;\n"
"    border-right-color: #cccccc;\n"
"}")
        self.recycle_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recycle_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.recycle_table.setObjectName("recycle_table")
        self.recycle_table.setColumnCount(7)
        self.recycle_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 5, item)
        self.recycle_table.horizontalHeader().setDefaultSectionSize(250)
        self.recycle_table.verticalHeader().setDefaultSectionSize(50)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 931, 91))
        self.widget.setStyleSheet("/* Main light gray container */\n"
"QWidget{\n"
"    background-color: #DADADA; /* light gray */\n"
"}")
        self.widget.setObjectName("widget")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(80, 0, 20, 91))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(90, 21, 1041, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(112, 8, 53, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(195, 8, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(780, 7, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Restore_btn = QtWidgets.QPushButton(self.widget)
        self.Restore_btn.setGeometry(QtCore.QRect(112, 34, 51, 51))
        self.Restore_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;      /* make background see-through */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;          /* light top/left edge */\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #555555;       /* dark bottom/right edge */\n"
"    border-right-color: #555555;\n"
"    border-radius: 4px;                  /* optional: rounded corners */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* invert border for “pressed” effect */\n"
"    border-top-color: #555555;\n"
"    border-left-color: #555555;\n"
"    border-bottom-color: #ffffff;\n"
"    border-right-color: #ffffff;\n"
"}")
        self.Restore_btn.setText("")
        self.Restore_btn.setObjectName("Restore_btn")
        self.Restore_all_btn = QtWidgets.QPushButton(self.widget)
        self.Restore_all_btn.setGeometry(QtCore.QRect(209, 34, 51, 51))
        self.Restore_all_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;      /* make background see-through */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;          /* light top/left edge */\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #555555;       /* dark bottom/right edge */\n"
"    border-right-color: #555555;\n"
"    border-radius: 4px;                  /* optional: rounded corners */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* invert border for “pressed” effect */\n"
"    border-top-color: #555555;\n"
"    border-left-color: #555555;\n"
"    border-bottom-color: #ffffff;\n"
"    border-right-color: #ffffff;\n"
"}")
        self.Restore_all_btn.setText("")
        self.Restore_all_btn.setObjectName("Restore_all_btn")
        self.Delete_permanently_btn = QtWidgets.QPushButton(self.widget)
        self.Delete_permanently_btn.setGeometry(QtCore.QRect(820, 34, 51, 51))
        self.Delete_permanently_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;      /* make background see-through */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;          /* light top/left edge */\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #555555;       /* dark bottom/right edge */\n"
"    border-right-color: #555555;\n"
"    border-radius: 4px;                  /* optional: rounded corners */\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* invert border for “pressed” effect */\n"
"    border-top-color: #555555;\n"
"    border-left-color: #555555;\n"
"    border-bottom-color: #ffffff;\n"
"    border-right-color: #ffffff;\n"
"}")
        self.Delete_permanently_btn.setText("")
        self.Delete_permanently_btn.setObjectName("Delete_permanently_btn")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(-1, 80, 1041, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(10, 15, 71, 61))
        self.label_14.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(f"{image_path}/Recycle Bin.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(112, 34, 51, 51))
        self.label_16.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(f"{image_path}/restore.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(210, 42, 51, 41))
        self.label_17.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(f"{image_path}/restore-all.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(820, 41, 51, 41))
        self.label_18.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(f"{image_path}/hard-delete.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_18.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.line_7.raise_()
        self.line_4.raise_()
        self.line_6.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Restore_btn.raise_()
        self.Restore_all_btn.raise_()
        self.Delete_permanently_btn.raise_()
        self.label_14.raise_()
        self.widget.raise_()
        self.recycle_table.raise_()
        RecycleBin.setCentralWidget(self.centralwidget)

        self.retranslateUi(RecycleBin)
        QtCore.QMetaObject.connectSlotsByName(RecycleBin)

    def retranslateUi(self, RecycleBin):
        _translate = QtCore.QCoreApplication.translate
        RecycleBin.setWindowTitle(_translate("Recycle Bin", "Recycle Bin"))
        item = self.recycle_table.verticalHeaderItem(0)
        item.setText(_translate("RecycleBin", "1"))
        item = self.recycle_table.horizontalHeaderItem(0)
        item.setText(_translate("RecycleBin", "Type of inventory"))
        item = self.recycle_table.horizontalHeaderItem(1)
        item.setText(_translate("RecycleBin", "Name - User"))
        item = self.recycle_table.horizontalHeaderItem(2)
        item.setText(_translate("RecycleBin", "Date"))
        item = self.recycle_table.horizontalHeaderItem(3)
        item.setText(_translate("RecycleBin", "Name - Client"))
        item = self.recycle_table.horizontalHeaderItem(4)
        item.setText(_translate("RecycleBin", "Time"))
        item = self.recycle_table.horizontalHeaderItem(5)
        item.setText(_translate("RecycleBin", "Chemical/Used"))
        item = self.recycle_table.horizontalHeaderItem(6)
        item.setText(_translate("RecycleBin", "Acutal chemical used"))
        __sortingEnabled = self.recycle_table.isSortingEnabled()
        self.recycle_table.setSortingEnabled(False)
        self.recycle_table.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("RecycleBin", "Restore"))
        self.label_8.setText(_translate("RecycleBin", "Restore All"))
        self.label_9.setText(_translate("RecycleBin", "Delete Permanently"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecycleBin = QtWidgets.QMainWindow()
    ui = Ui_RecycleBin()
    ui.setupUi(RecycleBin)
    RecycleBin.show()
    sys.exit(app.exec_())
