# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recycle_bin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

base_dir = os.path.dirname(__file__)
image_path = os.path.join(base_dir, "assets")

class Ui_RecycleBin(object):
    def setupUi(self, RecycleBin):
        RecycleBin.setObjectName("RecycleBin")
        RecycleBin.resize(931, 717)
        self.centralwidget = QtWidgets.QWidget(RecycleBin)
        self.centralwidget.setObjectName("centralwidget")
        self.recycle_table = QtWidgets.QTableWidget(self.centralwidget)
        self.recycle_table.setGeometry(QtCore.QRect(0, 90, 931, 631))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.recycle_table.setFont(font)
        self.recycle_table.setStyleSheet("QTableWidget {\n"
"    background-color: #F6FBF8;          /* soft green-tinted white */\n"
"    border: 1px solid #D6E8DD;          /* subtle modern border */\n"
"    gridline-color: #E3EFE8;\n"
"    font: 13pt \"Segoe UI\";\n"
"\n"
"    selection-background-color: #4CAF70;\n"
"    selection-color: white;\n"
"\n"
"    alternate-background-color: #EDF7F1;\n"
"}\n"
"\n"
"/* cells */\n"
"QTableWidget::item {\n"
"    padding: 10px;\n"
"    border: none;\n"
"    color: #1F2D23;\n"
"}\n"
"\n"
"/* hover (soft green highlight) */\n"
"QTableWidget::item:hover {\n"
"    background-color: #DFF3E6;\n"
"}\n"
"\n"
"/* selected */\n"
"QTableWidget::item:selected {\n"
"    background-color: #4CAF70;\n"
"    color: white;\n"
"}\n"
"\n"
"/* header (modern flat style) */\n"
"QHeaderView::section {\n"
"    background-color: #E4F1EA;\n"
"    color: #1F2D23;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    font: 10pt \"Segoe UI\";\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"/* row header hover (clickable feel) */\n"
"QHeaderView::section:vertical:hover {\n"
"    background-color: #CFE9D8;\n"
"}\n"
"\n"
"/* row header pressed */\n"
"QHeaderView::section:vertical:pressed {\n"
"    background-color: #4CAF70;\n"
"    color: white;\n"
"}\n"
"\n"
"/* corner */\n"
"QTableCornerButton::section {\n"
"    background-color: #E4F1EA;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Vertical ScrollBar */\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    width: 16px;                     /* ⬅ bigger */\n"
"    margin: 6px 2px 6px 2px;\n"
"}\n"
"\n"
"/* handle */\n"
"QScrollBar::handle:vertical {\n"
"    background: #CFE9D8;\n"
"    border-radius: 8px;\n"
"    min-height: 40px;               /* ⬅ bigger handle */\n"
"}\n"
"\n"
"/* hover */\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #AFCFBB;\n"
"}\n"
"\n"
"/* pressed */\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background: #4CAF70;\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"/* track */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Horizontal ScrollBar */\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    height: 16px;                   /* ⬅ bigger */\n"
"    margin: 2px 6px 2px 6px;\n"
"}\n"
"\n"
"/* handle */\n"
"QScrollBar::handle:horizontal {\n"
"    background: #CFE9D8;\n"
"    border-radius: 8px;\n"
"    min-width: 40px;                /* ⬅ bigger handle */\n"
"}\n"
"\n"
"/* hover */\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #AFCFBB;\n"
"}\n"
"\n"
"/* pressed */\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background: #4CAF70;\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"/* track */\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}")
        self.recycle_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recycle_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.recycle_table.setObjectName("recycle_table")
        self.recycle_table.setColumnCount(7)
        self.recycle_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.recycle_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.recycle_table.setItem(0, 5, item)
        self.recycle_table.horizontalHeader().setDefaultSectionSize(250)
        self.recycle_table.verticalHeader().setDefaultSectionSize(50)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 931, 91))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: #EEF7F2;   /* slightly darker than table */\n"
"}")
        self.widget.setObjectName("widget")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(80, 0, 20, 91))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(90, 21, 1041, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(112, 8, 53, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(195, 8, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(780, 7, 137, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.Restore_btn = QtWidgets.QPushButton(self.widget)
        self.Restore_btn.setGeometry(QtCore.QRect(112, 34, 51, 51))
        self.Restore_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #7CFFB2;\n"
"\n"
"    border: 1px solid #2F6B3F;   /* darker, visible green outline */\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* hover (subtle visible lift, no covering image) */\n"
"QPushButton:hover {\n"
"    background-color: rgba(47, 107, 63, 0.18);  /* soft green tint */\n"
"    border-color: #3A7F52;                      /* brighter border */\n"
"}\n"
"\n"
"/* pressed (stronger feedback but still transparent) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(47, 107, 63, 0.28);\n"
"    border-color: #1F4D2C;                      /* darker press */\n"
"}")
        self.Restore_btn.setText("")
        self.Restore_btn.setObjectName("Restore_btn")
        self.Restore_all_btn = QtWidgets.QPushButton(self.widget)
        self.Restore_all_btn.setGeometry(QtCore.QRect(209, 34, 51, 51))
        self.Restore_all_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #7CFFB2;\n"
"\n"
"    border: 1px solid #2F6B3F;   /* darker, visible green outline */\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* hover (subtle visible lift, no covering image) */\n"
"QPushButton:hover {\n"
"    background-color: rgba(47, 107, 63, 0.18);  /* soft green tint */\n"
"    border-color: #3A7F52;                      /* brighter border */\n"
"}\n"
"\n"
"/* pressed (stronger feedback but still transparent) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(47, 107, 63, 0.28);\n"
"    border-color: #1F4D2C;                      /* darker press */\n"
"}")
        self.Restore_all_btn.setText("")
        self.Restore_all_btn.setObjectName("Restore_all_btn")
        self.Delete_permanently_btn = QtWidgets.QPushButton(self.widget)
        self.Delete_permanently_btn.setGeometry(QtCore.QRect(820, 34, 51, 51))
        self.Delete_permanently_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #7CFFB2;\n"
"\n"
"    border: 1px solid #2F6B3F;   /* darker, visible green outline */\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"/* hover (subtle visible lift, no covering image) */\n"
"QPushButton:hover {\n"
"    background-color: rgba(47, 107, 63, 0.18);  /* soft green tint */\n"
"    border-color: #3A7F52;                      /* brighter border */\n"
"}\n"
"\n"
"/* pressed (stronger feedback but still transparent) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(47, 107, 63, 0.28);\n"
"    border-color: #1F4D2C;                      /* darker press */\n"
"}")
        self.Delete_permanently_btn.setText("")
        self.Delete_permanently_btn.setObjectName("Delete_permanently_btn")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(-1, 80, 1041, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(10, 15, 71, 61))
        self.label_14.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(f"{image_path}/Recycle Bin.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(112, 34, 51, 51))
        self.label_16.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(f"{image_path}/restore.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(210, 42, 51, 41))
        self.label_17.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(f"{image_path}/restore-all.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setGeometry(QtCore.QRect(820, 41, 51, 41))
        self.label_18.setStyleSheet("QLabel {\n"
"    background: transparent\n"
"}")
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(f"{image_path}/hard-delete.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_18.raise_()
        self.label_17.raise_()
        self.label_16.raise_()
        self.line_7.raise_()
        self.line_4.raise_()
        self.line_6.raise_()
        self.label.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Restore_btn.raise_()
        self.Restore_all_btn.raise_()
        self.Delete_permanently_btn.raise_()
        self.label_14.raise_()
        self.widget.raise_()
        self.recycle_table.raise_()
        RecycleBin.setCentralWidget(self.centralwidget)

        self.retranslateUi(RecycleBin)
        QtCore.QMetaObject.connectSlotsByName(RecycleBin)

    def retranslateUi(self, RecycleBin):
        _translate = QtCore.QCoreApplication.translate
        RecycleBin.setWindowTitle(_translate("RecycleBin", "RecyleBin"))
        item = self.recycle_table.verticalHeaderItem(0)
        item.setText(_translate("RecycleBin", "1"))
        item = self.recycle_table.horizontalHeaderItem(0)
        item.setText(_translate("RecycleBin", "Type of inventory"))
        item = self.recycle_table.horizontalHeaderItem(1)
        item.setText(_translate("RecycleBin", "Name - User"))
        item = self.recycle_table.horizontalHeaderItem(2)
        item.setText(_translate("RecycleBin", "Date"))
        item = self.recycle_table.horizontalHeaderItem(3)
        item.setText(_translate("RecycleBin", "Name - Client"))
        item = self.recycle_table.horizontalHeaderItem(4)
        item.setText(_translate("RecycleBin", "Time"))
        item = self.recycle_table.horizontalHeaderItem(5)
        item.setText(_translate("RecycleBin", "Chemical/Used"))
        item = self.recycle_table.horizontalHeaderItem(6)
        item.setText(_translate("RecycleBin", "Actual Chemical Used"))
        __sortingEnabled = self.recycle_table.isSortingEnabled()
        self.recycle_table.setSortingEnabled(False)
        self.recycle_table.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("RecycleBin", "Restore"))
        self.label_8.setText(_translate("RecycleBin", "Restore All"))
        self.label_9.setText(_translate("RecycleBin", "Delete Permanently"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecycleBin = QtWidgets.QMainWindow()
    ui = Ui_RecycleBin()
    ui.setupUi(RecycleBin)
    RecycleBin.show()
    sys.exit(app.exec_())
