# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard(object):
    def setupUi(self, Dashboard):
        Dashboard.setObjectName("Dashboard")
        Dashboard.resize(1462, 982)
        Dashboard.setStyleSheet("QMainWindow {\n"
"    background-color: #EBEBEB;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(864, -10, 241, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(682, -10, 181, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 69, 1381, 911))
        self.scrollArea.setStyleSheet("QScrollArea { background-color: #D9E9CF; border: none; border-right: 1px solid #DCE3DC; border-radius: 15px;\n"
"} QWidget { background-color: #D9E9CF; }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1379, 909))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.hours = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.hours.setGeometry(QtCore.QRect(100, 248, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.hours.setFont(font)
        self.hours.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hours.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.hours.setEditable(False)
        self.hours.setObjectName("hours")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.hours.addItem("")
        self.PM_or_AM = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.PM_or_AM.setGeometry(QtCore.QRect(300, 248, 81, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PM_or_AM.setFont(font)
        self.PM_or_AM.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PM_or_AM.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.PM_or_AM.setEditable(False)
        self.PM_or_AM.setObjectName("PM_or_AM")
        self.PM_or_AM.addItem("")
        self.PM_or_AM.addItem("")
        self.yearLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.yearLabel.setGeometry(QtCore.QRect(290, 140, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yearLabel.setFont(font)
        self.yearLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yearLabel.setTextFormat(QtCore.Qt.AutoText)
        self.yearLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yearLabel.setIndent(67)
        self.yearLabel.setObjectName("yearLabel")
        self.endTimeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.endTimeLabel.setGeometry(QtCore.QRect(40, 310, 33, 19))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.endTimeLabel.setFont(font)
        self.endTimeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.endTimeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.endTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.endTimeLabel.setIndent(67)
        self.endTimeLabel.setObjectName("endTimeLabel")
        self.time = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.time.setGeometry(QtCore.QRect(200, 248, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time.setFont(font)
        self.time.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.time.setEditable(False)
        self.time.setObjectName("time")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.time_2.setGeometry(QtCore.QRect(200, 298, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time_2.setFont(font)
        self.time_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.time_2.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.time_2.setEditable(False)
        self.time_2.setObjectName("time_2")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.time_2.addItem("")
        self.timeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.timeLabel.setGeometry(QtCore.QRect(26, 220, 233, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.timeLabel.setFont(font)
        self.timeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setIndent(67)
        self.timeLabel.setObjectName("timeLabel")
        self.nameLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.nameLabel.setGeometry(QtCore.QRect(27, 40, 291, 19))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nameLabel.setFont(font)
        self.nameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.nameLabel.setTextFormat(QtCore.Qt.AutoText)
        self.nameLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.nameLabel.setIndent(67)
        self.nameLabel.setObjectName("nameLabel")
        self.startTimeLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.startTimeLabel.setGeometry(QtCore.QRect(30, 260, 61, 19))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.startTimeLabel.setFont(font)
        self.startTimeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startTimeLabel.setTextFormat(QtCore.Qt.AutoText)
        self.startTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.startTimeLabel.setIndent(67)
        self.startTimeLabel.setObjectName("startTimeLabel")
        self.actualchemicalUsed = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.actualchemicalUsed.setGeometry(QtCore.QRect(10, 630, 381, 171))
        self.actualchemicalUsed.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F5F5;  /* ✅ clean light grey */\n"
"    gridline-color: #D8EDE0;\n"
"    border: none;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #1B4332;\n"
"    selection-background-color: #C6F6D5;\n"
"    selection-color: #1B4332;\n"
"\n"
"    /* ✅ green 3D frame */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QTableWidget::item { \n"
"    padding: 4px 8px; \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected { \n"
"    background-color: #C6F6D5; \n"
"    color: #1B4332; \n"
"}\n"
"\n"
"/* COLUMN HEADERS */\n"
"QHeaderView::section {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-right: 1px solid #1B4332;\n"
"    padding: 6px 8px;\n"
"    font: bold 11pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"/* ROW HEADERS */\n"
"QHeaderView::section:vertical {\n"
"    background-color: #F0F0F0;\n"
"    color: #1B4332;\n"
"    border-right: 1px solid #D1D9CC;\n"
"}\n"
"\n"
"/* HEADER AREA CLEANUP */\n"
"QHeaderView { \n"
"    background-color: transparent; \n"
"    border: none; \n"
"}\n"
"\n"
"/* SCROLLBAR */\n"
"\n"
"/* SCROLLBAR */\n"
"QScrollBar:vertical {\n"
"    background: #E8F0EC;   /* lighter track for contrast */\n"
"    width: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1B4332;   /* DARKER than header (#2F6B3F) */\n"
"    border-radius: 5px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover { \n"
"    background: #0F2A20;   /* very dark hover for clarity */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed { \n"
"    background: #081A13;   /* deepest press */\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical { \n"
"    height: 0; \n"
"}\n"
"\n"
"/* clean track */\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical { \n"
"    background: transparent; \n"
"}\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    background: #E8F0EC;\n"
"    height: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #1B4332;   /* darker than header */\n"
"    border-radius: 5px;\n"
"    min-width: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover { \n"
"    background: #0F2A20;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed { \n"
"    background: #081A13;\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal { \n"
"    width: 0; \n"
"}\n"
"\n"
"/* clean track */\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal { \n"
"    background: transparent; \n"
"}\n"
"\n"
"/* CORNER (top-left box) */\n"
"QTableCornerButton::section { \n"
"    background-color: #2D6A4F;\n"
"    border: none; \n"
"}")
        self.actualchemicalUsed.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.actualchemicalUsed.setObjectName("actualchemicalUsed")
        self.actualchemicalUsed.setColumnCount(3)
        self.actualchemicalUsed.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.actualchemicalUsed.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualchemicalUsed.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualchemicalUsed.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualchemicalUsed.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualchemicalUsed.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.actualchemicalUsed.setItem(4, 0, item)
        self.actualchemicalUsed.horizontalHeader().setDefaultSectionSize(250)
        self.actualchemicalUsed.horizontalHeader().setSortIndicatorShown(False)
        self.actualchemicalUsed.horizontalHeader().setStretchLastSection(False)
        self.actualchemicalUsed.verticalHeader().setDefaultSectionSize(40)
        self.chemLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.chemLabel.setGeometry(QtCore.QRect(20, 360, 323, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.chemLabel.setFont(font)
        self.chemLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chemLabel.setTextFormat(QtCore.Qt.AutoText)
        self.chemLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.chemLabel.setIndent(67)
        self.chemLabel.setObjectName("chemLabel")
        self.month = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.month.setGeometry(QtCore.QRect(95, 160, 81, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.month.setFont(font)
        self.month.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.month.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.month.setEditable(False)
        self.month.setObjectName("month")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.month.addItem("")
        self.nameofClientinput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.nameofClientinput.setGeometry(QtCore.QRect(18, 70, 371, 41))
        self.nameofClientinput.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    padding: 8px 16px 8px 36px;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #374151;\n"
"\n"
"    /* 3D GREEN BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"/* HOVER EFFECT */\n"
"QLineEdit:hover {\n"
"    background-color: #F0FAF4;   /* soft green hover tint */\n"
"    border-top-color: #D7F2DE;\n"
"    border-left-color: #D7F2DE;\n"
"    border-bottom-color: #1B4332; /* darker shadow for depth */\n"
"    border-right-color: #1B4332;\n"
"\n"
"    color: #2F3A34;\n"
"}\n"
"\n"
"/* CLICKED / ACTIVE (FOCUS) EFFECT */\n"
"QLineEdit:focus {\n"
"    background-color: #E3F3EA;   /* stronger active tint */\n"
"    border-top-color: #BFE8CC;\n"
"    border-left-color: #BFE8CC;\n"
"    border-bottom-color: #0F3D24; /* deep pressed effect */\n"
"    border-right-color: #0F3D24;\n"
"\n"
"    color: #10261C;\n"
"}")
        self.nameofClientinput.setObjectName("nameofClientinput")
        self.hours_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.hours_2.setGeometry(QtCore.QRect(100, 298, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.hours_2.setFont(font)
        self.hours_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hours_2.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.hours_2.setEditable(False)
        self.hours_2.setObjectName("hours_2")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.hours_2.addItem("")
        self.dateCalLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.dateCalLabel.setGeometry(QtCore.QRect(190, 140, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateCalLabel.setFont(font)
        self.dateCalLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateCalLabel.setTextFormat(QtCore.Qt.AutoText)
        self.dateCalLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateCalLabel.setIndent(67)
        self.dateCalLabel.setObjectName("dateCalLabel")
        self.monthLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.monthLabel.setGeometry(QtCore.QRect(90, 140, 81, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.monthLabel.setFont(font)
        self.monthLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.monthLabel.setTextFormat(QtCore.Qt.AutoText)
        self.monthLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthLabel.setIndent(67)
        self.monthLabel.setObjectName("monthLabel")
        self.year = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.year.setGeometry(QtCore.QRect(290, 160, 91, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.year.setFont(font)
        self.year.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.year.setEditable(False)
        self.year.setObjectName("year")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.year.addItem("")
        self.PM_or_AM_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.PM_or_AM_2.setGeometry(QtCore.QRect(300, 298, 81, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.PM_or_AM_2.setFont(font)
        self.PM_or_AM_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PM_or_AM_2.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.PM_or_AM_2.setEditable(False)
        self.PM_or_AM_2.setObjectName("PM_or_AM_2")
        self.PM_or_AM_2.addItem("")
        self.PM_or_AM_2.addItem("")
        self.chemicalUsed = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.chemicalUsed.setGeometry(QtCore.QRect(12, 380, 381, 171))
        self.chemicalUsed.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F5F5;  /* ✅ clean light grey */\n"
"    gridline-color: #D8EDE0;\n"
"    border: none;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #1B4332;\n"
"    selection-background-color: #C6F6D5;\n"
"    selection-color: #1B4332;\n"
"\n"
"    /* ✅ green 3D frame */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QTableWidget::item { \n"
"    padding: 4px 8px; \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected { \n"
"    background-color: #C6F6D5; \n"
"    color: #1B4332; \n"
"}\n"
"\n"
"/* COLUMN HEADERS */\n"
"QHeaderView::section {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-right: 1px solid #1B4332;\n"
"    padding: 6px 8px;\n"
"    font: bold 11pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"/* ROW HEADERS */\n"
"QHeaderView::section:vertical {\n"
"    background-color: #F0F0F0;\n"
"    color: #1B4332;\n"
"    border-right: 1px solid #D1D9CC;\n"
"}\n"
"\n"
"/* HEADER AREA CLEANUP */\n"
"QHeaderView { \n"
"    background-color: transparent; \n"
"    border: none; \n"
"}\n"
"\n"
"/* SCROLLBAR */\n"
"\n"
"/* SCROLLBAR */\n"
"QScrollBar:vertical {\n"
"    background: #E8F0EC;   /* lighter track for contrast */\n"
"    width: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1B4332;   /* DARKER than header (#2F6B3F) */\n"
"    border-radius: 5px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover { \n"
"    background: #0F2A20;   /* very dark hover for clarity */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed { \n"
"    background: #081A13;   /* deepest press */\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical { \n"
"    height: 0; \n"
"}\n"
"\n"
"/* clean track */\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical { \n"
"    background: transparent; \n"
"}\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    background: #E8F0EC;\n"
"    height: 11px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #1B4332;   /* darker than header */\n"
"    border-radius: 5px;\n"
"    min-width: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover { \n"
"    background: #0F2A20;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed { \n"
"    background: #081A13;\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal { \n"
"    width: 0; \n"
"}\n"
"\n"
"/* clean track */\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal { \n"
"    background: transparent; \n"
"}\n"
"\n"
"/* CORNER (top-left box) */\n"
"QTableCornerButton::section { \n"
"    background-color: #2D6A4F;\n"
"    border: none; \n"
"}")
        self.chemicalUsed.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chemicalUsed.setObjectName("chemicalUsed")
        self.chemicalUsed.setColumnCount(3)
        self.chemicalUsed.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.chemicalUsed.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chemicalUsed.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chemicalUsed.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chemicalUsed.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chemicalUsed.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chemicalUsed.setItem(4, 0, item)
        self.chemicalUsed.horizontalHeader().setDefaultSectionSize(250)
        self.chemicalUsed.horizontalHeader().setSortIndicatorShown(False)
        self.chemicalUsed.horizontalHeader().setStretchLastSection(False)
        self.chemicalUsed.verticalHeader().setDefaultSectionSize(40)
        self.dateLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.dateLabel.setGeometry(QtCore.QRect(26, 120, 237, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dateLabel.setFont(font)
        self.dateLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateLabel.setTextFormat(QtCore.Qt.AutoText)
        self.dateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateLabel.setIndent(67)
        self.dateLabel.setObjectName("dateLabel")
        self.confirmButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.confirmButton.setGeometry(QtCore.QRect(90, 860, 211, 41))
        self.confirmButton.setStyleSheet("QPushButton {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #cccccc;\n"
"    border-right-color: #cccccc;\n"
"    border-radius: 15px;\n"
"    padding: 12px 20px;\n"
"    font: bold 13pt \"Segoe UI\";\n"
"    letter-spacing: 1px;\n"
"}\n"
"\n"
"/* HOVER EFFECT */\n"
"QPushButton:hover {\n"
"    background-color: #285C36; /* slightly darker green */\n"
"    border-top-color: #E6E6E6;\n"
"    border-left-color: #E6E6E6;\n"
"    border-bottom-color: #B3B3B3;\n"
"    border-right-color: #B3B3B3;\n"
"}\n"
"\n"
"/* CLICK / PRESSED EFFECT */\n"
"QPushButton:pressed {\n"
"    background-color: #0D2B1F; /* deep pressed green */\n"
"    border-top-color: #1A1A1A;  /* inverted depth */\n"
"    border-left-color: #1A1A1A;\n"
"    border-bottom-color: #4A4A4A;\n"
"    border-right-color: #4A4A4A;\n"
"\n"
"    padding-top: 14px;   /* press down illusion */\n"
"    padding-left: 22px;\n"
"}")
        self.confirmButton.setObjectName("confirmButton")
        self.date = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.date.setGeometry(QtCore.QRect(197, 160, 71, 42))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.date.setFont(font)
        self.date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date.setStyleSheet("QComboBox {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 8px;\n"
"    padding: 5px 10px;\n"
"    color: #1A3C2A;\n"
"    font: 11pt \"Segoe UI\";\n"
"    min-height: 28px;\n"
"\n"
"    /* GREEN 3D BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    background-color: #D6EBDD;\n"
"    border-top-color: #C6E6D3;\n"
"    border-left-color: #C6E6D3;\n"
"    border-bottom-color: #0E3B21;\n"
"    border-right-color: #0E3B21;\n"
"    color: #0B2F1B;\n"
"}\n"
"\n"
"/* FOCUS EFFECT */\n"
"QComboBox:focus {\n"
"    background-color: #EAF7EE;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #1B4332;\n"
"    border-right-color: #1B4332;\n"
"}\n"
"\n"
"/* dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #C6F6D5;\n"
"    border-radius: 6px;\n"
"    selection-background-color: #2D6A4F;\n"
"    selection-color: #ffffff;\n"
"    font: 10pt \"Segoe UI\";\n"
"}")
        self.date.setEditable(False)
        self.date.setObjectName("date")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.date.addItem("")
        self.actualChemLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.actualChemLabel.setGeometry(QtCore.QRect(15, 610, 409, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actualChemLabel.setFont(font)
        self.actualChemLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.actualChemLabel.setTextFormat(QtCore.Qt.AutoText)
        self.actualChemLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.actualChemLabel.setIndent(67)
        self.actualChemLabel.setObjectName("actualChemLabel")
        self.contentPanel = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.contentPanel.setGeometry(QtCore.QRect(400, 10, 961, 891))
        self.contentPanel.setStyleSheet("QWidget { background-color: #ECFAE5; border-radius: 15px;}")
        self.contentPanel.setObjectName("contentPanel")
        self.tableListahan = QtWidgets.QTableWidget(self.contentPanel)
        self.tableListahan.setGeometry(QtCore.QRect(15, 71, 931, 801))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableListahan.setFont(font)
        self.tableListahan.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F5F5;  /* ✅ clean light grey */\n"
"    gridline-color: #D8EDE0;\n"
"    border: none;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #1B4332;\n"
"    selection-background-color: #C6F6D5;\n"
"    selection-color: #1B4332;\n"
"\n"
"    /* ✅ green 3D frame */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #E9F5EC;\n"
"    border-left-color: #E9F5EC;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"QTableWidget::item { \n"
"    padding: 4px 8px; \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected { \n"
"    background-color: #C6F6D5; \n"
"    color: #1B4332; \n"
"}\n"
"\n"
"/* COLUMN HEADERS */\n"
"QHeaderView::section {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-right: 1px solid #1B4332;\n"
"    padding: 6px 8px;\n"
"    font: bold 12pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"}\n"
"\n"
"/* ROW HEADERS */\n"
"QHeaderView::section:vertical {\n"
"    background-color: #F0F0F0;\n"
"    color: #1B4332;\n"
"    border-right: 1px solid #D1D9CC;\n"
"}\n"
"\n"
"/* HEADER AREA CLEANUP */\n"
"QHeaderView { \n"
"    background-color: transparent; \n"
"    border: none; \n"
"}\n"
"\n"
"\n"
"/* SCROLLBAR */\n"
"QScrollBar:vertical {\n"
"    background: #E2EAE5;   /* darker track for better contrast */\n"
"    width: 10px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #1F4D2C;   /* darker green handle */\n"
"\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover { \n"
"    background: #163A22;   /* even darker hover */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed { \n"
"    background: #0F2A18;   /* deep press effect */\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical { \n"
"    height: 0; \n"
"}\n"
"\n"
"/* clean page area */\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical { \n"
"    background: transparent; \n"
"}\n"
"\n"
"\n"
"/* HORIZONTAL SCROLLBAR */\n"
"QScrollBar:horizontal {\n"
"    background: #E2EAE5;\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #1F4D2C;\n"
"    min-width: 25px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover { \n"
"    background: #163A22;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed { \n"
"    background: #0F2A18;\n"
"}\n"
"\n"
"/* remove arrows */\n"
"QScrollBar::add-line:horizontal, \n"
"QScrollBar::sub-line:horizontal { \n"
"    width: 0; \n"
"}\n"
"\n"
"/* clean page area */\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal { \n"
"    background: transparent; \n"
"}\n"
"/* CORNER (top-left box) */\n"
"QTableCornerButton::section { \n"
"    background-color: #2D6A4F;\n"
"    border: none; \n"
"}")
        self.tableListahan.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableListahan.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableListahan.setObjectName("tableListahan")
        self.tableListahan.setColumnCount(8)
        self.tableListahan.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableListahan.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.tableListahan.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListahan.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableListahan.setHorizontalHeaderItem(7, item)
        self.tableListahan.horizontalHeader().setDefaultSectionSize(255)
        self.tableListahan.horizontalHeader().setMinimumSectionSize(40)
        self.tableListahan.verticalHeader().setDefaultSectionSize(60)
        self.searchDate = QtWidgets.QLineEdit(self.contentPanel)
        self.searchDate.setGeometry(QtCore.QRect(66, 20, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.searchDate.setFont(font)
        self.searchDate.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px 8px 36px;\n"
"    font: 11pt \"Segoe UI\";\n"
"    color: #2F3A34;  /* slightly darker for better contrast */\n"
"\n"
"    /* 3D GREEN BORDER */\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #C6F6D5;\n"
"    border-left-color: #C6F6D5;\n"
"    border-bottom-color: #2D6A4F;\n"
"    border-right-color: #2D6A4F;\n"
"}\n"
"\n"
"/* HOVER EFFECT (darker but still soft) */\n"
"QLineEdit:hover {\n"
"    background-color: #E3F2E9;   /* darker green tint */\n"
"    border-top-color: #BFE8CC;\n"
"    border-left-color: #BFE8CC;\n"
"    border-bottom-color: #1B4332; /* stronger shadow */\n"
"    border-right-color: #1B4332;\n"
"\n"
"    color: #1F2E27; /* keep readable */\n"
"}\n"
"\n"
"/* CLICKED / ACTIVE (FOCUS) EFFECT */\n"
"QLineEdit:focus {\n"
"    background-color: #D6EDE1;   /* noticeably darker active state */\n"
"    border-top-color: #A9D8BA;\n"
"    border-left-color: #A9D8BA;\n"
"    border-bottom-color: #0E3B21; /* deep pressed look */\n"
"    border-right-color: #0E3B21;\n"
"\n"
"    color: #10261C; /* very readable dark green-black */\n"
"}")
        self.searchDate.setObjectName("searchDate")
        self.confirmButton_2 = QtWidgets.QPushButton(self.contentPanel)
        self.confirmButton_2.setGeometry(QtCore.QRect(360, 21, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirmButton_2.setFont(font)
        self.confirmButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #9B0F06;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #cccccc;\n"
"    border-right-color: #cccccc;\n"
"    padding: 12px 20px;\n"
"    font: bold 8pt \"Segoe UI\";\n"
"    letter-spacing: 1px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"/* HOVER EFFECT */\n"
"QPushButton:hover {\n"
"    background-color: #9B0F06; /* slightly darker green */\n"
"    border-top-color: #E6E6E6;\n"
"    border-left-color: #E6E6E6;\n"
"    border-bottom-color: #B3B3B3;\n"
"    border-right-color: #B3B3B3;\n"
"}\n"
"\n"
"/* CLICK / PRESSED EFFECT */\n"
"QPushButton:pressed {\n"
"    background-color: #9B0F06; /* deep pressed green */\n"
"    border-top-color: #1A1A1A;  /* inverted depth */\n"
"    border-left-color: #1A1A1A;\n"
"    border-bottom-color: #4A4A4A;\n"
"    border-right-color: #4A4A4A;\n"
"\n"
"    padding-top: 14px;   /* press down illusion */\n"
"    padding-left: 22px;\n"
"}")
        self.confirmButton_2.setObjectName("confirmButton_2")
        self.confirmButton_3 = QtWidgets.QPushButton(self.contentPanel)
        self.confirmButton_3.setGeometry(QtCore.QRect(585, 21, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.confirmButton_3.setFont(font)
        self.confirmButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #DA4848;\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top-color: #ffffff;\n"
"    border-left-color: #ffffff;\n"
"    border-bottom-color: #cccccc;\n"
"    border-right-color: #cccccc;\n"
"    padding: 12px 20px;\n"
"    font: bold 8pt \"Segoe UI\";\n"
"    letter-spacing: 1px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"/* HOVER EFFECT */\n"
"QPushButton:hover {\n"
"    background-color: #DA4848; /* slightly darker green */\n"
"    border-top-color: #E6E6E6;\n"
"    border-left-color: #E6E6E6;\n"
"    border-bottom-color: #B3B3B3;\n"
"    border-right-color: #B3B3B3;\n"
"}\n"
"\n"
"/* CLICK / PRESSED EFFECT */\n"
"QPushButton:pressed {\n"
"    background-color: #DA4848; /* deep pressed green */\n"
"    border-top-color: #1A1A1A;  /* inverted depth */\n"
"    border-left-color: #1A1A1A;\n"
"    border-bottom-color: #4A4A4A;\n"
"    border-right-color: #4A4A4A;\n"
"\n"
"    padding-top: 14px;   /* press down illusion */\n"
"    padding-left: 22px;\n"
"}")
        self.confirmButton_3.setObjectName("confirmButton_3")
        self.searchIcon = QtWidgets.QLabel(self.contentPanel)
        self.searchIcon.setGeometry(QtCore.QRect(4, 22, 71, 41))
        self.searchIcon.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.searchIcon.setText("")
        self.searchIcon.setPixmap(QtGui.QPixmap("searchIcon.png"))
        self.searchIcon.setScaledContents(True)
        self.searchIcon.setObjectName("searchIcon")
        self.trashIcon = QtWidgets.QLabel(self.contentPanel)
        self.trashIcon.setGeometry(QtCore.QRect(535, 19, 71, 41))
        self.trashIcon.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.trashIcon.setText("")
        self.trashIcon.setPixmap(QtGui.QPixmap("trashIcon.png"))
        self.trashIcon.setScaledContents(True)
        self.trashIcon.setObjectName("trashIcon")
        self.pdfIcon = QtWidgets.QLabel(self.contentPanel)
        self.pdfIcon.setGeometry(QtCore.QRect(305, 20, 71, 41))
        self.pdfIcon.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.pdfIcon.setText("")
        self.pdfIcon.setPixmap(QtGui.QPixmap("pdfIcon.png"))
        self.pdfIcon.setScaledContents(True)
        self.pdfIcon.setObjectName("pdfIcon")
        self.AdminName = QtWidgets.QLabel(self.contentPanel)
        self.AdminName.setGeometry(QtCore.QRect(830, 27, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.AdminName.setFont(font)
        self.AdminName.setStyleSheet("QLabel { color: #1B4332; font: bold 10pt \'Segoe UI\'; background: transparent; }")
        self.AdminName.setAlignment(QtCore.Qt.AlignCenter)
        self.AdminName.setObjectName("AdminName")
        self.adminIcon = QtWidgets.QLabel(self.contentPanel)
        self.adminIcon.setGeometry(QtCore.QRect(890, 17, 71, 41))
        self.adminIcon.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.adminIcon.setText("")
        self.adminIcon.setPixmap(QtGui.QPixmap("adminIcon.png"))
        self.adminIcon.setScaledContents(True)
        self.adminIcon.setObjectName("adminIcon")
        self.ViewActChem = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.ViewActChem.setGeometry(QtCore.QRect(26, 810, 351, 36))
        self.ViewActChem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewActChem.setStyleSheet("QPushButton {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    letter-spacing: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover { background-color: #1B4332; }\n"
"QPushButton:pressed { background-color: #081A13; }")
        self.ViewActChem.setObjectName("ViewActChem")
        self.ViewChem = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.ViewChem.setGeometry(QtCore.QRect(20, 560, 361, 36))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ViewChem.setFont(font)
        self.ViewChem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ViewChem.setStyleSheet("QPushButton {\n"
"    background-color: #2F6B3F;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    font: bold 10pt \"Segoe UI\";\n"
"    letter-spacing: 1px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover { background-color: #1B4332; }\n"
"QPushButton:pressed { background-color: #081A13; }")
        self.ViewChem.setObjectName("ViewChem")
        self.HeaderTreatment = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.HeaderTreatment.setGeometry(QtCore.QRect(1, 4, 261, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.HeaderTreatment.setFont(font)
        self.HeaderTreatment.setStyleSheet("QLabel { color: #1B4332; font: bold 16pt \'Segoe UI\'; background: transparent; }")
        self.HeaderTreatment.setObjectName("HeaderTreatment")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setGeometry(QtCore.QRect(253, 2, 51, 31))
        self.label_11.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("filesIcon.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setGeometry(QtCore.QRect(96, 865, 51, 31))
        self.label_12.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("contentIcon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.headerBar = QtWidgets.QFrame(self.centralwidget)
        self.headerBar.setGeometry(QtCore.QRect(-10, 0, 1381, 71))
        self.headerBar.setStyleSheet("QFrame {\n"
"    background-color: #2D6A4F;\n"
"    padding: 8px;\n"
"    border-radius: 10px;\n"
"    margin: 6px;\n"
"}")
        self.headerBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.headerBar.setObjectName("headerBar")
        self.appTitle_2 = QtWidgets.QLabel(self.headerBar)
        self.appTitle_2.setGeometry(QtCore.QRect(53, 10, 121, 51))
        self.appTitle_2.setStyleSheet("QLabel { color: #ffffff; font: bold 15pt \'Segoe UI\'; background: transparent; }")
        self.appTitle_2.setObjectName("appTitle_2")
        self.label = QtWidgets.QLabel(self.headerBar)
        self.label.setGeometry(QtCore.QRect(1, -4, 81, 81))
        self.label.setStyleSheet("QLabel {\n"
"background: transparent;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        Dashboard.setCentralWidget(self.centralwidget)
        self.toolBar_files = QtWidgets.QToolBar(Dashboard)
        font = QtGui.QFont()
        font.setPointSize(3)
        self.toolBar_files.setFont(font)
        self.toolBar_files.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBar_files.setTabletTracking(False)
        self.toolBar_files.setStyleSheet("QToolBar {\n"
"    background-color: #2D6A4F;\n"
"    border: 1px solid #1F4D2C;\n"
"    padding: 8px;\n"
"    spacing: 6px;\n"
"    border-radius: 10px;\n"
"    margin: 6px;\n"
"}\n"
"\n"
"/* Toolbar buttons */\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QToolButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.15);\n"
"}\n"
"\n"
"/* Click / pressed effect */\n"
"QToolButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.25);\n"
"    padding-top: 7px;   /* slight “press down” illusion */\n"
"    padding-left: 6px;\n"
"}")
        self.toolBar_files.setMovable(False)
        self.toolBar_files.setIconSize(QtCore.QSize(48, 48))
        self.toolBar_files.setFloatable(False)
        self.toolBar_files.setObjectName("toolBar_files")
        Dashboard.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_files)
        self.actionTREATMENT = QtWidgets.QAction(Dashboard)
        self.actionTREATMENT.setObjectName("actionTREATMENT")
        self.actionINSPECTION = QtWidgets.QAction(Dashboard)
        self.actionINSPECTION.setObjectName("actionINSPECTION")
        self.actionRECYCLE_BIN = QtWidgets.QAction(Dashboard)
        self.actionRECYCLE_BIN.setObjectName("actionRECYCLE_BIN")
        self.actionPDF_STORAGE = QtWidgets.QAction(Dashboard)
        self.actionPDF_STORAGE.setObjectName("actionPDF_STORAGE")
        self.actionLOGOUT = QtWidgets.QAction(Dashboard)
        self.actionLOGOUT.setObjectName("actionLOGOUT")
        self.actionTREATMENT_2 = QtWidgets.QAction(Dashboard)
        self.actionTREATMENT_2.setObjectName("actionTREATMENT_2")
        self.actionINSPECTION_2 = QtWidgets.QAction(Dashboard)
        self.actionINSPECTION_2.setObjectName("actionINSPECTION_2")
        self.actionPDF_STORAGE_3 = QtWidgets.QAction(Dashboard)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PDF.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPDF_STORAGE_3.setIcon(icon)
        self.actionPDF_STORAGE_3.setObjectName("actionPDF_STORAGE_3")
        self.recycle_bin = QtWidgets.QAction(Dashboard)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Recycle Bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recycle_bin.setIcon(icon1)
        self.recycle_bin.setObjectName("recycle_bin")
        self.PDF_storage = QtWidgets.QAction(Dashboard)
        self.PDF_storage.setIcon(icon)
        self.PDF_storage.setObjectName("PDF_storage")
        self.logout = QtWidgets.QAction(Dashboard)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon2)
        self.logout.setObjectName("logout")
        self.treatment = QtWidgets.QAction(Dashboard)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Treatment.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treatment.setIcon(icon3)
        self.treatment.setObjectName("treatment")
        self.inspection = QtWidgets.QAction(Dashboard)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Inspection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inspection.setIcon(icon4)
        self.inspection.setObjectName("inspection")
        self.toolBar_files.addAction(self.inspection)
        self.toolBar_files.addAction(self.treatment)
        self.toolBar_files.addAction(self.recycle_bin)
        self.toolBar_files.addAction(self.actionPDF_STORAGE_3)
        self.toolBar_files.addAction(self.logout)

        self.retranslateUi(Dashboard)
        QtCore.QMetaObject.connectSlotsByName(Dashboard)

    def retranslateUi(self, Dashboard):
        _translate = QtCore.QCoreApplication.translate
        Dashboard.setWindowTitle(_translate("Dashboard", "Dashboard"))
        self.hours.setItemText(0, _translate("Dashboard", "01"))
        self.hours.setItemText(1, _translate("Dashboard", "02"))
        self.hours.setItemText(2, _translate("Dashboard", "03"))
        self.hours.setItemText(3, _translate("Dashboard", "04"))
        self.hours.setItemText(4, _translate("Dashboard", "05"))
        self.hours.setItemText(5, _translate("Dashboard", "06"))
        self.hours.setItemText(6, _translate("Dashboard", "07"))
        self.hours.setItemText(7, _translate("Dashboard", "08"))
        self.hours.setItemText(8, _translate("Dashboard", "09"))
        self.hours.setItemText(9, _translate("Dashboard", "10"))
        self.hours.setItemText(10, _translate("Dashboard", "11"))
        self.hours.setItemText(11, _translate("Dashboard", "12"))
        self.PM_or_AM.setItemText(0, _translate("Dashboard", "PM"))
        self.PM_or_AM.setItemText(1, _translate("Dashboard", "AM"))
        self.yearLabel.setText(_translate("Dashboard", "YEAR"))
        self.endTimeLabel.setText(_translate("Dashboard", "END"))
        self.time.setItemText(0, _translate("Dashboard", "00"))
        self.time.setItemText(1, _translate("Dashboard", "1"))
        self.time.setItemText(2, _translate("Dashboard", "2"))
        self.time.setItemText(3, _translate("Dashboard", "3"))
        self.time.setItemText(4, _translate("Dashboard", "4"))
        self.time.setItemText(5, _translate("Dashboard", "5"))
        self.time.setItemText(6, _translate("Dashboard", "6"))
        self.time.setItemText(7, _translate("Dashboard", "7"))
        self.time.setItemText(8, _translate("Dashboard", "8"))
        self.time.setItemText(9, _translate("Dashboard", "9"))
        self.time.setItemText(10, _translate("Dashboard", "10"))
        self.time.setItemText(11, _translate("Dashboard", "11"))
        self.time.setItemText(12, _translate("Dashboard", "12"))
        self.time.setItemText(13, _translate("Dashboard", "13"))
        self.time.setItemText(14, _translate("Dashboard", "14"))
        self.time.setItemText(15, _translate("Dashboard", "15"))
        self.time.setItemText(16, _translate("Dashboard", "16"))
        self.time.setItemText(17, _translate("Dashboard", "17"))
        self.time.setItemText(18, _translate("Dashboard", "18"))
        self.time.setItemText(19, _translate("Dashboard", "19"))
        self.time.setItemText(20, _translate("Dashboard", "20"))
        self.time.setItemText(21, _translate("Dashboard", "21"))
        self.time.setItemText(22, _translate("Dashboard", "22"))
        self.time.setItemText(23, _translate("Dashboard", "23"))
        self.time.setItemText(24, _translate("Dashboard", "24"))
        self.time.setItemText(25, _translate("Dashboard", "25"))
        self.time.setItemText(26, _translate("Dashboard", "26"))
        self.time.setItemText(27, _translate("Dashboard", "27"))
        self.time.setItemText(28, _translate("Dashboard", "28"))
        self.time.setItemText(29, _translate("Dashboard", "29"))
        self.time.setItemText(30, _translate("Dashboard", "30"))
        self.time.setItemText(31, _translate("Dashboard", "31"))
        self.time.setItemText(32, _translate("Dashboard", "32"))
        self.time.setItemText(33, _translate("Dashboard", "33"))
        self.time.setItemText(34, _translate("Dashboard", "34"))
        self.time.setItemText(35, _translate("Dashboard", "35"))
        self.time.setItemText(36, _translate("Dashboard", "36"))
        self.time.setItemText(37, _translate("Dashboard", "37"))
        self.time.setItemText(38, _translate("Dashboard", "38"))
        self.time.setItemText(39, _translate("Dashboard", "39"))
        self.time.setItemText(40, _translate("Dashboard", "40"))
        self.time.setItemText(41, _translate("Dashboard", "41"))
        self.time.setItemText(42, _translate("Dashboard", "42"))
        self.time.setItemText(43, _translate("Dashboard", "43"))
        self.time.setItemText(44, _translate("Dashboard", "44"))
        self.time.setItemText(45, _translate("Dashboard", "45"))
        self.time.setItemText(46, _translate("Dashboard", "46"))
        self.time.setItemText(47, _translate("Dashboard", "47"))
        self.time.setItemText(48, _translate("Dashboard", "48"))
        self.time.setItemText(49, _translate("Dashboard", "49"))
        self.time.setItemText(50, _translate("Dashboard", "50"))
        self.time.setItemText(51, _translate("Dashboard", "51"))
        self.time.setItemText(52, _translate("Dashboard", "52"))
        self.time.setItemText(53, _translate("Dashboard", "53"))
        self.time.setItemText(54, _translate("Dashboard", "54"))
        self.time.setItemText(55, _translate("Dashboard", "55"))
        self.time.setItemText(56, _translate("Dashboard", "56"))
        self.time.setItemText(57, _translate("Dashboard", "57"))
        self.time.setItemText(58, _translate("Dashboard", "58"))
        self.time.setItemText(59, _translate("Dashboard", "59"))
        self.time_2.setItemText(0, _translate("Dashboard", "00"))
        self.time_2.setItemText(1, _translate("Dashboard", "1"))
        self.time_2.setItemText(2, _translate("Dashboard", "2"))
        self.time_2.setItemText(3, _translate("Dashboard", "3"))
        self.time_2.setItemText(4, _translate("Dashboard", "4"))
        self.time_2.setItemText(5, _translate("Dashboard", "5"))
        self.time_2.setItemText(6, _translate("Dashboard", "6"))
        self.time_2.setItemText(7, _translate("Dashboard", "7"))
        self.time_2.setItemText(8, _translate("Dashboard", "8"))
        self.time_2.setItemText(9, _translate("Dashboard", "9"))
        self.time_2.setItemText(10, _translate("Dashboard", "10"))
        self.time_2.setItemText(11, _translate("Dashboard", "11"))
        self.time_2.setItemText(12, _translate("Dashboard", "12"))
        self.time_2.setItemText(13, _translate("Dashboard", "13"))
        self.time_2.setItemText(14, _translate("Dashboard", "14"))
        self.time_2.setItemText(15, _translate("Dashboard", "15"))
        self.time_2.setItemText(16, _translate("Dashboard", "16"))
        self.time_2.setItemText(17, _translate("Dashboard", "17"))
        self.time_2.setItemText(18, _translate("Dashboard", "18"))
        self.time_2.setItemText(19, _translate("Dashboard", "19"))
        self.time_2.setItemText(20, _translate("Dashboard", "20"))
        self.time_2.setItemText(21, _translate("Dashboard", "21"))
        self.time_2.setItemText(22, _translate("Dashboard", "22"))
        self.time_2.setItemText(23, _translate("Dashboard", "23"))
        self.time_2.setItemText(24, _translate("Dashboard", "24"))
        self.time_2.setItemText(25, _translate("Dashboard", "25"))
        self.time_2.setItemText(26, _translate("Dashboard", "26"))
        self.time_2.setItemText(27, _translate("Dashboard", "27"))
        self.time_2.setItemText(28, _translate("Dashboard", "28"))
        self.time_2.setItemText(29, _translate("Dashboard", "29"))
        self.time_2.setItemText(30, _translate("Dashboard", "30"))
        self.time_2.setItemText(31, _translate("Dashboard", "31"))
        self.time_2.setItemText(32, _translate("Dashboard", "32"))
        self.time_2.setItemText(33, _translate("Dashboard", "33"))
        self.time_2.setItemText(34, _translate("Dashboard", "34"))
        self.time_2.setItemText(35, _translate("Dashboard", "35"))
        self.time_2.setItemText(36, _translate("Dashboard", "36"))
        self.time_2.setItemText(37, _translate("Dashboard", "37"))
        self.time_2.setItemText(38, _translate("Dashboard", "38"))
        self.time_2.setItemText(39, _translate("Dashboard", "39"))
        self.time_2.setItemText(40, _translate("Dashboard", "40"))
        self.time_2.setItemText(41, _translate("Dashboard", "41"))
        self.time_2.setItemText(42, _translate("Dashboard", "42"))
        self.time_2.setItemText(43, _translate("Dashboard", "43"))
        self.time_2.setItemText(44, _translate("Dashboard", "44"))
        self.time_2.setItemText(45, _translate("Dashboard", "45"))
        self.time_2.setItemText(46, _translate("Dashboard", "46"))
        self.time_2.setItemText(47, _translate("Dashboard", "47"))
        self.time_2.setItemText(48, _translate("Dashboard", "48"))
        self.time_2.setItemText(49, _translate("Dashboard", "49"))
        self.time_2.setItemText(50, _translate("Dashboard", "50"))
        self.time_2.setItemText(51, _translate("Dashboard", "51"))
        self.time_2.setItemText(52, _translate("Dashboard", "52"))
        self.time_2.setItemText(53, _translate("Dashboard", "53"))
        self.time_2.setItemText(54, _translate("Dashboard", "54"))
        self.time_2.setItemText(55, _translate("Dashboard", "55"))
        self.time_2.setItemText(56, _translate("Dashboard", "56"))
        self.time_2.setItemText(57, _translate("Dashboard", "57"))
        self.time_2.setItemText(58, _translate("Dashboard", "58"))
        self.time_2.setItemText(59, _translate("Dashboard", "59"))
        self.time_2.setItemText(60, _translate("Dashboard", "60"))
        self.timeLabel.setText(_translate("Dashboard", "TIME OF TREATMENT"))
        self.nameLabel.setText(_translate("Dashboard", "NAME OF CLIENT - TREATMENT"))
        self.startTimeLabel.setText(_translate("Dashboard", "START"))
        item = self.actualchemicalUsed.verticalHeaderItem(0)
        item.setText(_translate("Dashboard", "1"))
        item = self.actualchemicalUsed.verticalHeaderItem(1)
        item.setText(_translate("Dashboard", "2"))
        item = self.actualchemicalUsed.verticalHeaderItem(2)
        item.setText(_translate("Dashboard", "3"))
        item = self.actualchemicalUsed.verticalHeaderItem(3)
        item.setText(_translate("Dashboard", "4"))
        item = self.actualchemicalUsed.verticalHeaderItem(4)
        item.setText(_translate("Dashboard", "5"))
        item = self.actualchemicalUsed.horizontalHeaderItem(0)
        item.setText(_translate("Dashboard", "Actual Chemical/s on Hand"))
        item = self.actualchemicalUsed.horizontalHeaderItem(1)
        item.setText(_translate("Dashboard", "Quantity"))
        item = self.actualchemicalUsed.horizontalHeaderItem(2)
        item.setText(_translate("Dashboard", "Remarks"))
        __sortingEnabled = self.actualchemicalUsed.isSortingEnabled()
        self.actualchemicalUsed.setSortingEnabled(False)
        self.actualchemicalUsed.setSortingEnabled(__sortingEnabled)
        self.chemLabel.setText(_translate("Dashboard", "CHEMICALS USED — TREATMENT"))
        self.month.setItemText(0, _translate("Dashboard", "1"))
        self.month.setItemText(1, _translate("Dashboard", "2"))
        self.month.setItemText(2, _translate("Dashboard", "3"))
        self.month.setItemText(3, _translate("Dashboard", "4"))
        self.month.setItemText(4, _translate("Dashboard", "5"))
        self.month.setItemText(5, _translate("Dashboard", "6"))
        self.month.setItemText(6, _translate("Dashboard", "7"))
        self.month.setItemText(7, _translate("Dashboard", "8"))
        self.month.setItemText(8, _translate("Dashboard", "9"))
        self.month.setItemText(9, _translate("Dashboard", "10"))
        self.month.setItemText(10, _translate("Dashboard", "11"))
        self.month.setItemText(11, _translate("Dashboard", "12"))
        self.nameofClientinput.setPlaceholderText(_translate("Dashboard", "Ex: Eorico"))
        self.hours_2.setItemText(0, _translate("Dashboard", "01"))
        self.hours_2.setItemText(1, _translate("Dashboard", "02"))
        self.hours_2.setItemText(2, _translate("Dashboard", "03"))
        self.hours_2.setItemText(3, _translate("Dashboard", "04"))
        self.hours_2.setItemText(4, _translate("Dashboard", "05"))
        self.hours_2.setItemText(5, _translate("Dashboard", "06"))
        self.hours_2.setItemText(6, _translate("Dashboard", "07"))
        self.hours_2.setItemText(7, _translate("Dashboard", "08"))
        self.hours_2.setItemText(8, _translate("Dashboard", "09"))
        self.hours_2.setItemText(9, _translate("Dashboard", "10"))
        self.hours_2.setItemText(10, _translate("Dashboard", "11"))
        self.hours_2.setItemText(11, _translate("Dashboard", "12"))
        self.dateCalLabel.setText(_translate("Dashboard", "DATE"))
        self.monthLabel.setText(_translate("Dashboard", "MONTH"))
        self.year.setItemText(0, _translate("Dashboard", "2015"))
        self.year.setItemText(1, _translate("Dashboard", "2016"))
        self.year.setItemText(2, _translate("Dashboard", "2017"))
        self.year.setItemText(3, _translate("Dashboard", "2018"))
        self.year.setItemText(4, _translate("Dashboard", "2019"))
        self.year.setItemText(5, _translate("Dashboard", "2020"))
        self.year.setItemText(6, _translate("Dashboard", "2021"))
        self.year.setItemText(7, _translate("Dashboard", "2022"))
        self.year.setItemText(8, _translate("Dashboard", "2023"))
        self.year.setItemText(9, _translate("Dashboard", "2024"))
        self.year.setItemText(10, _translate("Dashboard", "2025"))
        self.year.setItemText(11, _translate("Dashboard", "2026"))
        self.year.setItemText(12, _translate("Dashboard", "2027"))
        self.year.setItemText(13, _translate("Dashboard", "2028"))
        self.year.setItemText(14, _translate("Dashboard", "2029"))
        self.year.setItemText(15, _translate("Dashboard", "2030"))
        self.PM_or_AM_2.setItemText(0, _translate("Dashboard", "PM"))
        self.PM_or_AM_2.setItemText(1, _translate("Dashboard", "AM"))
        item = self.chemicalUsed.verticalHeaderItem(0)
        item.setText(_translate("Dashboard", "1"))
        item = self.chemicalUsed.verticalHeaderItem(1)
        item.setText(_translate("Dashboard", "2"))
        item = self.chemicalUsed.verticalHeaderItem(2)
        item.setText(_translate("Dashboard", "3"))
        item = self.chemicalUsed.verticalHeaderItem(3)
        item.setText(_translate("Dashboard", "4"))
        item = self.chemicalUsed.verticalHeaderItem(4)
        item.setText(_translate("Dashboard", "5"))
        item = self.chemicalUsed.horizontalHeaderItem(0)
        item.setText(_translate("Dashboard", "Chemical/s Used"))
        item = self.chemicalUsed.horizontalHeaderItem(1)
        item.setText(_translate("Dashboard", "Quantity"))
        item = self.chemicalUsed.horizontalHeaderItem(2)
        item.setText(_translate("Dashboard", "Remarks"))
        __sortingEnabled = self.chemicalUsed.isSortingEnabled()
        self.chemicalUsed.setSortingEnabled(False)
        self.chemicalUsed.setSortingEnabled(__sortingEnabled)
        self.dateLabel.setText(_translate("Dashboard", "DATE OF TREATMENT"))
        self.confirmButton.setText(_translate("Dashboard", " SAVE RECORD"))
        self.date.setItemText(0, _translate("Dashboard", "1"))
        self.date.setItemText(1, _translate("Dashboard", "2"))
        self.date.setItemText(2, _translate("Dashboard", "3"))
        self.date.setItemText(3, _translate("Dashboard", "4"))
        self.date.setItemText(4, _translate("Dashboard", "5"))
        self.date.setItemText(5, _translate("Dashboard", "6"))
        self.date.setItemText(6, _translate("Dashboard", "7"))
        self.date.setItemText(7, _translate("Dashboard", "8"))
        self.date.setItemText(8, _translate("Dashboard", "9"))
        self.date.setItemText(9, _translate("Dashboard", "10"))
        self.date.setItemText(10, _translate("Dashboard", "11"))
        self.date.setItemText(11, _translate("Dashboard", "12"))
        self.date.setItemText(12, _translate("Dashboard", "13"))
        self.date.setItemText(13, _translate("Dashboard", "14"))
        self.date.setItemText(14, _translate("Dashboard", "15"))
        self.date.setItemText(15, _translate("Dashboard", "16"))
        self.date.setItemText(16, _translate("Dashboard", "17"))
        self.date.setItemText(17, _translate("Dashboard", "18"))
        self.date.setItemText(18, _translate("Dashboard", "19"))
        self.date.setItemText(19, _translate("Dashboard", "20"))
        self.date.setItemText(20, _translate("Dashboard", "21"))
        self.date.setItemText(21, _translate("Dashboard", "22"))
        self.date.setItemText(22, _translate("Dashboard", "23"))
        self.date.setItemText(23, _translate("Dashboard", "24"))
        self.date.setItemText(24, _translate("Dashboard", "25"))
        self.date.setItemText(25, _translate("Dashboard", "26"))
        self.date.setItemText(26, _translate("Dashboard", "27"))
        self.date.setItemText(27, _translate("Dashboard", "28"))
        self.date.setItemText(28, _translate("Dashboard", "29"))
        self.date.setItemText(29, _translate("Dashboard", "30"))
        self.date.setItemText(30, _translate("Dashboard", "31"))
        self.actualChemLabel.setText(_translate("Dashboard", " ACTUAL CHEMICALS ON HAND - TREATMENT"))
        item = self.tableListahan.verticalHeaderItem(0)
        item.setText(_translate("Dashboard", "1"))
        item = self.tableListahan.horizontalHeaderItem(0)
        item.setText(_translate("Dashboard", "Name of User"))
        item = self.tableListahan.horizontalHeaderItem(1)
        item.setText(_translate("Dashboard", "Date of Treatment"))
        item = self.tableListahan.horizontalHeaderItem(2)
        item.setText(_translate("Dashboard", "Name of Client"))
        item = self.tableListahan.horizontalHeaderItem(3)
        item.setText(_translate("Dashboard", "Time of Treatment"))
        item = self.tableListahan.horizontalHeaderItem(4)
        item.setText(_translate("Dashboard", "Chemical/s Used"))
        item = self.tableListahan.horizontalHeaderItem(5)
        item.setText(_translate("Dashboard", "Actual Chemical/s Used"))
        item = self.tableListahan.horizontalHeaderItem(6)
        item.setText(_translate("Dashboard", "Remarks"))
        item = self.tableListahan.horizontalHeaderItem(7)
        item.setText(_translate("Dashboard", "Edit"))
        self.searchDate.setPlaceholderText(_translate("Dashboard", "Search client or date..."))
        self.confirmButton_2.setText(_translate("Dashboard", " CONVERT TO PDF"))
        self.confirmButton_3.setText(_translate("Dashboard", " TRASH"))
        self.AdminName.setText(_translate("Dashboard", "ADMIN"))
        self.ViewActChem.setText(_translate("Dashboard", "View"))
        self.ViewChem.setText(_translate("Dashboard", "View"))
        self.HeaderTreatment.setText(_translate("Dashboard", "NEW TREATMENT ENTRY"))
        self.appTitle_2.setText(_translate("Dashboard", "RAIONN"))
        self.toolBar_files.setWindowTitle(_translate("Dashboard", "toolBar_2"))
        self.actionTREATMENT.setText(_translate("Dashboard", "TREATMENT"))
        self.actionINSPECTION.setText(_translate("Dashboard", "INSPECTION"))
        self.actionRECYCLE_BIN.setText(_translate("Dashboard", "RECYCLE BIN"))
        self.actionPDF_STORAGE.setText(_translate("Dashboard", "PDF STORAGE"))
        self.actionLOGOUT.setText(_translate("Dashboard", "LOGOUT"))
        self.actionTREATMENT_2.setText(_translate("Dashboard", "TREATMENT"))
        self.actionINSPECTION_2.setText(_translate("Dashboard", "INSPECTION"))
        self.actionPDF_STORAGE_3.setText(_translate("Dashboard", "PDF"))
        self.actionPDF_STORAGE_3.setShortcut(_translate("Dashboard", "P"))
        self.recycle_bin.setText(_translate("Dashboard", "RECYCLE BIN"))
        self.PDF_storage.setText(_translate("Dashboard", "PDF STORAGE"))
        self.logout.setText(_translate("Dashboard", "LOGOUT"))
        self.treatment.setText(_translate("Dashboard", "TREATMENT"))
        self.inspection.setText(_translate("Dashboard", "INSPECTION"))
import bg main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dashboard = QtWidgets.QMainWindow()
    ui = Ui_Dashboard()
    ui.setupUi(Dashboard)
    Dashboard.show()
    sys.exit(app.exec_())
